export type CategoriaEsperienza =
  | "Natura"
  | "Mare"
  | "Gastronomia"
  | "Cultura"
  | "Sport"
  | "Benessere"
  | "Artigianato";

export type Difficolta = "Facile" | "Media" | "Difficile";

export type Esperienza = {
  id: string;
  titolo: string;
  categoria: CategoriaEsperienza;
  luogo: string;
  comune: string;
  descrizione: string;
  difficolta?: Difficolta;
  durata?: string;
  prezzo: string;
  inEvidenza?: boolean;
  linkEsterno?: string;
  tags?: string[];
  imgKeywords?: string; // keywords per Unsplash (es. "kayak,sea,italy")
};

export const CATEGORIE_ESPERIENZA: CategoriaEsperienza[] = [
  "Natura", "Mare", "Gastronomia", "Cultura", "Sport", "Benessere", "Artigianato",
];

export const STILE_CATEGORIA: Record<
  CategoriaEsperienza,
  { bg: string; color: string; gradient: string }
> = {
  Natura:      { bg: "#dcfce7", color: "#166534", gradient: "linear-gradient(135deg, #22c55e, #10b981)" },
  Mare:        { bg: "#dbeafe", color: "#1e40af", gradient: "linear-gradient(135deg, #3b82f6, #22d3ee)" },
  Gastronomia: { bg: "#fef3c7", color: "#92400e", gradient: "linear-gradient(135deg, #fb923c, #fbbf24)" },
  Cultura:     { bg: "#ede9fe", color: "#6b21a8", gradient: "linear-gradient(135deg, #a855f7, #818cf8)" },
  Sport:       { bg: "#fee2e2", color: "#991b1b", gradient: "linear-gradient(135deg, #f87171, #fb923c)" },
  Benessere:   { bg: "#fce7f3", color: "#9d174d", gradient: "linear-gradient(135deg, #f472b6, #c084fc)" },
  Artigianato: { bg: "#f3f4f6", color: "#374151", gradient: "linear-gradient(135deg, #9ca3af, #6b7280)" },
};

// Keywords di default per categoria (usate se l'esperienza non ha imgKeywords)
export const IMG_KEYWORDS_CATEGORIA: Record<CategoriaEsperienza, string> = {
  Natura:      "nature,forest,trail,italy,hiking",
  Mare:        "sea,coast,italy,mediterranean,ocean",
  Gastronomia: "food,italy,traditional,gourmet,cooking",
  Cultura:     "ruins,museum,italy,history,ancient",
  Sport:       "outdoor,adventure,sport,italy,nature",
  Benessere:   "spa,wellness,relax,italy,thermal",
  Artigianato: "crafts,artisan,pottery,italy,handmade",
};

export const esperienze: Esperienza[] = [

  // ── NATURA ────────────────────────────────────────────────────────────────

  {
    id: "trekking-monte-cervati",
    titolo: "Trekking sul Monte Cervati",
    categoria: "Natura",
    luogo: "Monte Cervati – 1.898 m slm",
    comune: "Sanza",
    descrizione: "Ascendi il tetto del Cilento, la cima più alta a 1.898 m. Il percorso attraversa faggete centenarie, praterie d'alta quota e offre una vista panoramica su tutto il Parco Nazionale, il Golfo di Policastro e l'Appennino Lucano. In vetta sorge il Santuario della Madonna del Sacro Monte, meta di pellegrinaggio.",
    difficolta: "Difficile",
    durata: "7–8 ore (A/R)",
    prezzo: "Gratuito",
    inEvidenza: true,
    tags: ["trekking", "montagna", "panorama", "santuario"],
    imgKeywords: "mountain,summit,hiking,italy,peak",
  },
  {
    id: "grotta-pertosa-auletta",
    titolo: "Grotte di Pertosa-Auletta",
    categoria: "Natura",
    luogo: "Grotte di Pertosa",
    comune: "Pertosa",
    descrizione: "Le uniche grotte d'Italia visitabili in barca: un fiume sotterraneo ti porta nelle profondità della terra tra stalattiti millenarie, sale cristalline e laghi nascosti. Un sito di straordinaria bellezza con percorsi guidati di diversa lunghezza, adatti a tutte le età.",
    difficolta: "Facile",
    durata: "1,5–2 ore",
    prezzo: "Da €13/persona",
    inEvidenza: true,
    linkEsterno: "https://www.grottedipertosa-auletta.it",
    tags: ["grotte", "fiume sotterraneo", "barca", "geologia"],
    imgKeywords: "cave,stalactite,underground,geology,italy",
  },
  {
    id: "grotta-castelcivita",
    titolo: "Grotta di Castelcivita",
    categoria: "Natura",
    luogo: "Contrada Grotticelle",
    comune: "Controne",
    descrizione: "Terza grotta d'Italia per sviluppo turistico, con oltre 4,8 km di gallerie esplorate. La visita guidata percorre 1 km tra ambienti di rara bellezza: la Sala del Sipario, il Lago Verde, il Colonnato. Reperti paleolitici testimoniano la presenza umana 30.000 anni fa.",
    difficolta: "Facile",
    durata: "1,5 ore",
    prezzo: "€12/persona",
    inEvidenza: true,
    linkEsterno: "https://www.grottadicastelcivita.com",
    tags: ["grotte", "paleolitico", "geologia", "storia"],
    imgKeywords: "cave,underground,stalactite,karst,italy",
  },
  {
    id: "gole-calore-felitto",
    titolo: "Gole del Calore Lucano – Felitto",
    categoria: "Natura",
    luogo: "Gole del Calore",
    comune: "Felitto",
    descrizione: "Un canyon naturale scavato dal fiume Calore nel cuore del Parco Nazionale. Il trekking segue il corso d'acqua tra pareti rocciose alte anche 100 m, pozze di smeraldo e vegetazione rigogliosa. Uno spettacolo naturale poco conosciuto, ideale per chi ama la natura incontaminata.",
    difficolta: "Media",
    durata: "3–4 ore",
    prezzo: "Gratuito",
    tags: ["canyon", "river", "trekking", "natura selvaggia"],
    imgKeywords: "canyon,river,gorge,italy,nature",
  },
  {
    id: "cascate-faraone-pisciotta",
    titolo: "Cascate del Faraone",
    categoria: "Natura",
    luogo: "Contrada Faraone",
    comune: "Pisciotta",
    descrizione: "Raggiungibili tramite un piacevole sentiero tra ulivi secolari, le Cascate del Faraone sono una serie di salti d'acqua che si gettano in pozze naturali color smeraldo. Meta ideale per un bagno rinfrescante in estate, in un contesto naturale di grande bellezza tra uliveti e macchia mediterranea.",
    difficolta: "Facile",
    durata: "2 ore",
    prezzo: "Gratuito",
    tags: ["cascate", "bagno", "natura", "estate"],
    imgKeywords: "waterfall,italy,nature,swimming,fresh",
  },
  {
    id: "canyon-mingardo-camerota",
    titolo: "Canyon del Mingardo",
    categoria: "Natura",
    luogo: "Fiume Mingardo",
    comune: "Camerota",
    descrizione: "Il Mingardo ha scavato nel tempo un suggestivo canyon nella roccia calcarea del Cilento costiero. Il percorso lungo il fiume porta a pozze di acqua cristallina perfette per il bagno, con scenari degni di un film d'avventura. Accesso da Licusati o da Marina di Camerota.",
    difficolta: "Media",
    durata: "4 ore",
    prezzo: "Gratuito",
    tags: ["canyon", "fiume", "trekking", "bagno naturale"],
    imgKeywords: "canyon,river,rocks,italy,adventure",
  },
  {
    id: "oasi-wwf-morigerati",
    titolo: "Oasi WWF – Sorgente Bussento",
    categoria: "Natura",
    luogo: "Sorgente del Bussento",
    comune: "Morigerati",
    descrizione: "Il fiume Bussento scompare sottoterra e riemerge spettacolarmente nella roccia calcarea di Morigerati, formando una sorgente carsica di straordinaria bellezza. L'oasi WWF ospita lontre, aironi, cormorani e una vegetazione riparia lussureggiante. Visita guidata disponibile in estate.",
    difficolta: "Facile",
    durata: "1,5 ore",
    prezzo: "Da €3/persona",
    inEvidenza: true,
    linkEsterno: "https://www.wwf.it/oasi",
    tags: ["wwf", "sorgente", "lontra", "carsismo"],
    imgKeywords: "spring,river,nature,wildlife,italy",
  },
  {
    id: "sentiero-pellegrino-monte-sacro",
    titolo: "Sentiero del Pellegrino – Monte Gelbison",
    categoria: "Natura",
    luogo: "Monte Gelbison – 1.705 m",
    comune: "Novi Velia",
    descrizione: "Antico cammino dei pellegrini verso il Santuario della Madonna del Gelbison, uno dei più importanti del Sud Italia. Il sentiero attraversa boschi di castagni e faggi, offrendo viste spettacolari sul Cilento e sul Vallo di Diano. La vetta si raggiunge anche in auto dalla strada panoramica.",
    difficolta: "Media",
    durata: "5–6 ore",
    prezzo: "Gratuito",
    tags: ["pellegrinaggio", "santuario", "bosco", "panorama"],
    imgKeywords: "pilgrimage,mountain,shrine,italy,forest",
  },
  {
    id: "trekking-capo-palinuro",
    titolo: "Trekking al Faro di Palinuro",
    categoria: "Natura",
    luogo: "Capo Palinuro",
    comune: "Centola",
    descrizione: "Il promontorio di Palinuro è uno dei più suggestivi del Mediterraneo, con i suoi archi naturali, grotte marine e scogliere a picco sul mare. Il sentiero costiero porta al faro storico con viste mozzafiato sul golfo. Al tramonto, i colori del cielo sul mare sono indimenticabili.",
    difficolta: "Media",
    durata: "3 ore",
    prezzo: "Gratuito",
    inEvidenza: true,
    tags: ["costa", "faro", "panorama", "tramonto"],
    imgKeywords: "cape,lighthouse,coast,mediterranean,sunset",
  },
  {
    id: "costa-infreschi-camerota",
    titolo: "Costa degli Infreschi e della Masseta",
    categoria: "Natura",
    luogo: "Costa degli Infreschi",
    comune: "Camerota",
    descrizione: "Riserva naturale integrale: nessuna strada, nessuna struttura, solo natura selvaggia. La costa è raggiungibile solo a piedi o in barca, con calette segrete, acque smeraldo e fondali incontaminati. Uno dei tratti di costa più incontaminati d'Italia, Patrimonio Naturale Protetto.",
    difficolta: "Media",
    durata: "4–5 ore",
    prezzo: "Gratuito",
    inEvidenza: true,
    tags: ["riserva", "selvaggio", "calette", "incontaminato"],
    imgKeywords: "wild,coast,cove,italy,pristine",
  },
  {
    id: "monte-stella-trekking",
    titolo: "Trekking sul Monte Stella",
    categoria: "Natura",
    luogo: "Monte Stella – 1.130 m",
    comune: "Santa Marina",
    descrizione: "La sentinella del Cilento costiero domina il Golfo di Policastro con una vista a 360°. Dal mare alla vetta attraverso uliveti, macchia mediterranea e faggeta. In cima si trova una cappella votiva e un antico eliporto militare. Vista stupenda sul Golfo e sull'isola di Dino.",
    difficolta: "Media",
    durata: "4 ore (A/R)",
    prezzo: "Gratuito",
    tags: ["panorama", "golfo di policastro", "oliveto", "faggeta"],
    imgKeywords: "hill,panorama,olive,italy,sea",
  },
  {
    id: "oasi-persano",
    titolo: "Riserva Naturale di Persano",
    categoria: "Natura",
    luogo: "Tenuta Persano",
    comune: "Serre",
    descrizione: "Una delle più importanti riserve faunistiche del Sud Italia, con cervi, daini, cinghiali e una ricchissima avifauna sul fiume Sele. Visite guidate con guardie forestali tra boschi ripariali e prati umidi. Il birdwatching è eccezionale in primavera e autunno.",
    difficolta: "Facile",
    durata: "2–3 ore",
    prezzo: "Gratuito (accesso limitato)",
    tags: ["birdwatching", "fauna", "riserva", "sele"],
    imgKeywords: "wildlife,nature,reserve,deer,italy",
  },
  {
    id: "fiume-bussento-casaletto-spartano",
    titolo: "Sorgenti del Bussento – Valle del Fiume",
    categoria: "Natura",
    luogo: "Valle del Bussento",
    comune: "Casaletto Spartano",
    descrizione: "Percorso lungo il fiume Bussento nella sua parte alta, tra boschi di ontani e carpini, pozze naturali e rapide. Un sentiero poco frequentato che porta a piscine naturali dove fare il bagno in completa solitudine. Ideale tra giugno e settembre.",
    difficolta: "Facile",
    durata: "2,5 ore",
    prezzo: "Gratuito",
    tags: ["fiume", "bagno naturale", "bosco", "escursione"],
    imgKeywords: "stream,forest,swimming,nature,italy",
  },
  {
    id: "riserva-alento",
    titolo: "Lago e Riserva del Fiume Alento",
    categoria: "Natura",
    luogo: "Lago dell'Alento",
    comune: "Prignano Cilento",
    descrizione: "Il lago artificiale dell'Alento immerso nel verde dei colli cilentani è un'oasi di pace per pescatori, birdwatcher e amanti della natura. I sentieri intorno al lago offrono viste pittoresche, con aironi, martin pescatori e folaghe. Possibilità di pesca sportiva con permesso.",
    difficolta: "Facile",
    durata: "2 ore",
    prezzo: "Gratuito",
    tags: ["lago", "birdwatching", "pesca", "natura"],
    imgKeywords: "lake,italy,birdwatching,nature,peaceful",
  },
  {
    id: "boschi-pollino-confine",
    titolo: "Bosco della Canala e Valle del Tanagro",
    categoria: "Natura",
    luogo: "Valle del Tanagro",
    comune: "Teggiano",
    descrizione: "La Valle del Tanagro, al confine tra Campania e Basilicata, è uno dei corridoi ecologici più importanti del Sud. Foreste miste di querce, cerri e castagni ospitano lupi, lontre e aquile. Sentieri poco battuti per chi cerca natura autentica lontano dalla folla.",
    difficolta: "Media",
    durata: "3–5 ore",
    prezzo: "Gratuito",
    tags: ["bosco", "fauna", "lupo", "valle"],
    imgKeywords: "oak,forest,valley,italy,wildlife",
  },

  // ── MARE ──────────────────────────────────────────────────────────────────

  {
    id: "kayak-grotte-palinuro",
    titolo: "Kayak nelle Grotte Marine di Palinuro",
    categoria: "Mare",
    luogo: "Porto di Palinuro",
    comune: "Centola",
    descrizione: "Le grotte marine di Palinuro sono tra le più belle del Mediterraneo: archi naturali, la Grotta Azzurra, la Grotta del Sangue con il suo particolare effetto luminoso rosso. Un'avventura in kayak tra formazioni rocciose millenarie e acque cristalline, guidata da istruttori certificati.",
    difficolta: "Facile",
    durata: "3 ore",
    prezzo: "Da €35/persona",
    inEvidenza: true,
    tags: ["kayak", "grotte", "mare", "avventura"],
    imgKeywords: "kayak,sea,cave,italy,mediterranean",
  },
  {
    id: "snorkeling-amp-castellabate",
    titolo: "Snorkeling nell'Area Marina Protetta di Castellabate",
    categoria: "Mare",
    luogo: "AMP Punta Licosa",
    comune: "Castellabate",
    descrizione: "L'Area Marina Protetta di Castellabate tutela uno dei tratti di mare più integri del Tirreno. Snorkeling guidato tra posidonie, saraghi, cernie, polpi e stelle marine. Le acque di Punta Licosa sono cristalline tutto l'anno. Attrezzatura inclusa, disponibile per adulti e bambini.",
    difficolta: "Facile",
    durata: "2,5 ore",
    prezzo: "Da €30/persona",
    inEvidenza: true,
    tags: ["snorkeling", "amp", "posidonia", "fauna marina"],
    imgKeywords: "snorkeling,italy,clear,sea,marine",
  },
  {
    id: "diving-punta-licosa",
    titolo: "Immersioni a Punta Licosa",
    categoria: "Mare",
    luogo: "Punta Licosa – Isola della Licosa",
    comune: "Castellabate",
    descrizione: "L'Isola della Licosa e i fondali circostanti offrono una biodiversità marina eccezionale: gorgonie rosse, corallo rosso, aragoste, murene e branchi di ricciole. Centro diving locale con brevetti PADI, guided dives e noleggio completo attrezzatura. Adatto da principianti a subacquei esperti.",
    difficolta: "Media",
    durata: "3–4 ore",
    prezzo: "Da €50/persona",
    tags: ["diving", "subacquea", "gorgonie", "corallo"],
    imgKeywords: "diving,underwater,coral,italy,fish",
  },
  {
    id: "gita-barca-palinuro",
    titolo: "Gita in Barca alle Grotte di Palinuro",
    categoria: "Mare",
    luogo: "Porto di Palinuro",
    comune: "Centola",
    descrizione: "Il tour classico di Palinuro: circumnavigazione del promontorio con visita alle grotte marine più famose — Grotta Azzurra, Grotta Fosforescente, Arco Naturale di Palinuro. Soste per bagno in calette inaccessibili a piedi. Un'esperienza imperdibile nel Cilento marino.",
    difficolta: "Facile",
    durata: "4 ore",
    prezzo: "Da €25/persona",
    inEvidenza: true,
    tags: ["barca", "grotte", "calette", "tour"],
    imgKeywords: "boat,cave,italy,coast,excursion",
  },
  {
    id: "sup-acciaroli",
    titolo: "Stand Up Paddle ad Acciaroli",
    categoria: "Mare",
    luogo: "Spiaggia di Acciaroli",
    comune: "Pollica",
    descrizione: "Acciaroli, il borgo marinaro che ispirò Hemingway, è la cornice perfetta per esplorare la costa in SUP. Noleggio tavole e corsi per principianti. Le acque calme della baia permettono di raggiungere cale nascoste inaccessibili a piedi. Tramonto in SUP: un'esperienza unica.",
    difficolta: "Facile",
    durata: "2 ore",
    prezzo: "Da €20/ora",
    tags: ["sup", "paddle", "acciaroli", "tramonto"],
    imgKeywords: "sup,paddleboard,sea,italy,bay",
  },
  {
    id: "pesca-alici-menaica",
    titolo: "Pesca delle Alici di Menaica con i Pescatori",
    categoria: "Mare",
    luogo: "Porto di Pisciotta",
    comune: "Pisciotta",
    descrizione: "Un'esperienza unica al mondo: accompagnare i pescatori di Pisciotta nella pesca notturna delle alici con la rete menaica, una tecnica antichissima tramandata da generazioni. Le alici di Menaica sono Presidio Slow Food, tra i prodotti ittici più pregiati d'Italia. Partenza al tramonto, rientro all'alba.",
    difficolta: "Facile",
    durata: "Intera notte",
    prezzo: "Da €40/persona",
    inEvidenza: true,
    tags: ["pesca", "alici di menaica", "slow food", "tradizione"],
    imgKeywords: "fishing,boat,night,italy,traditional",
  },
  {
    id: "escursione-costa-infreschi-barca",
    titolo: "Tour in Barca – Costa degli Infreschi",
    categoria: "Mare",
    luogo: "Marina di Camerota",
    comune: "Camerota",
    descrizione: "La Costa degli Infreschi è accessibile solo dal mare. Il tour in barca porta nelle calette più segrete della riserva naturale: la Spiaggia della Ficara, la Cala di Melito, il Porto degli Infreschi. Soste per snorkeling e nuoto in acque incontaminate di un blu irreale.",
    difficolta: "Facile",
    durata: "5 ore",
    prezzo: "Da €35/persona",
    inEvidenza: true,
    tags: ["barca", "riserva", "calette segrete", "snorkeling"],
    imgKeywords: "boat,cove,italy,secret,turquoise",
  },
  {
    id: "immersioni-camerota",
    titolo: "Diving a Camerota – Fondali Incontaminati",
    categoria: "Mare",
    luogo: "Marina di Camerota",
    comune: "Camerota",
    descrizione: "I fondali di Camerota sono tra i più ricchi di biodiversità del Tirreno Meridionale. Centri subacquei locali propongono immersioni guidate tra siti di grande interesse: grotte sottomarine, relitti storici, praterie di posidonia e canyon sommersi. Brevetti PADI disponibili.",
    difficolta: "Media",
    durata: "3 ore",
    prezzo: "Da €55/persona",
    tags: ["diving", "fondali", "relitti", "grotte marine"],
    imgKeywords: "scuba,underwater,italy,sea,diving",
  },
  {
    id: "whale-watching-golfo",
    titolo: "Whale Watching nel Golfo di Policastro",
    categoria: "Mare",
    luogo: "Golfo di Policastro",
    comune: "Sapri",
    descrizione: "Il Santuario dei Cetacei Pelagos protegge il Tirreno come patrimonio internazionale. Da Sapri, tour in barca per osservare capodogli, delfini striati, tursiopi e, in estate, balenottere comuni. Tour condotti da biologi marini con rilascio dati scientifici.",
    difficolta: "Facile",
    durata: "4–5 ore",
    prezzo: "Da €40/persona",
    inEvidenza: true,
    tags: ["balene", "delfini", "santuario cetacei", "barca"],
    imgKeywords: "whale,dolphin,boat,italy,ocean",
  },
  {
    id: "kitesurf-paestum",
    titolo: "Kitesurf a Capaccio-Paestum",
    categoria: "Mare",
    luogo: "Lido Laura – Capaccio",
    comune: "Capaccio-Paestum",
    descrizione: "La spiaggia di Capaccio-Paestum è uno dei migliori spot di kitesurf del Sud Italia, grazie ai venti termici costanti e al mare basso e sicuro. Scuola di kitesurf con istruttori FIV: corsi base e avanzati, noleggio attrezzatura completa. Stagione: aprile–ottobre.",
    difficolta: "Media",
    durata: "3 ore",
    prezzo: "Da €60/lezione",
    tags: ["kitesurf", "vento", "sport acquatico", "paestum"],
    imgKeywords: "kitesurf,wind,beach,italy,sport",
  },
  {
    id: "catamarano-tramonto-sapri",
    titolo: "Crociera al Tramonto in Catamarano",
    categoria: "Mare",
    luogo: "Porto di Sapri",
    comune: "Sapri",
    descrizione: "Aperitivo a bordo con vista sul Golfo di Policastro e il promontorio del Cilento durante un magnifico tramonto sul mare. La crociera tocca le calette più belle del golfo, con possibilità di bagno. Un'esperienza romantica e rilassante, con prodotti tipici locali inclusi.",
    difficolta: "Facile",
    durata: "3 ore",
    prezzo: "Da €45/persona",
    tags: ["catamarano", "tramonto", "aperitivo", "relax"],
    imgKeywords: "catamaran,sunset,sea,italy,luxury",
  },
  {
    id: "tour-barca-castellabate",
    titolo: "Tour in Barca – San Marco di Castellabate",
    categoria: "Mare",
    luogo: "San Marco di Castellabate",
    comune: "Castellabate",
    descrizione: "Il borgo marinaro di San Marco è tra i più pittoreschi del Cilento. Il tour in barca percorre la costa dell'Area Marina Protetta, con soste a Punta Licosa, sull'isolotto con la torre di avvistamento, e in calette di straordinaria bellezza. Snorkeling attrezzato incluso.",
    difficolta: "Facile",
    durata: "3,5 ore",
    prezzo: "Da €30/persona",
    tags: ["barca", "calette", "marina protetta", "snorkeling"],
    imgKeywords: "boat,village,coast,italy,mediterranean",
  },

  // ── GASTRONOMIA ───────────────────────────────────────────────────────────

  {
    id: "mozzarella-bufala-paestum",
    titolo: "Mozzarella di Bufala Campana DOP – Visita al Caseificio",
    categoria: "Gastronomia",
    luogo: "Piana del Sele – Capaccio",
    comune: "Capaccio-Paestum",
    descrizione: "La Piana del Sele è la patria della vera Mozzarella di Bufala Campana DOP. Visita ai caseifici storici: assisti alla lavorazione artigianale, dalla filatura a mano alla degustazione di mozzarella freschissima, burrata, ricotta di bufala e scamorza. Un percorso sensoriale unico.",
    difficolta: "Facile",
    durata: "2 ore",
    prezzo: "Da €15/persona",
    inEvidenza: true,
    tags: ["mozzarella", "bufala", "caseificio", "dop"],
    imgKeywords: "mozzarella,buffalo,cheese,italy,food",
  },
  {
    id: "olio-extravergine-cilento-dop",
    titolo: "Degustazione Olio Extravergine DOP Cilento",
    categoria: "Gastronomia",
    luogo: "Frantoi del Cilento",
    comune: "Vallo della Lucania",
    descrizione: "Il Cilento produce uno dei migliori oli d'Italia: il Cilento DOP. Tour nei frantoi storici con visita agli uliveti millenari (cultivar Pisciottana, Carpellese, Rotondella), dimostrazione della frangitura e degustazione guidata con abbinamenti ai prodotti tipici. Disponibile in autunno durante la raccolta.",
    difficolta: "Facile",
    durata: "2,5 ore",
    prezzo: "Da €20/persona",
    inEvidenza: true,
    tags: ["olio", "dop", "frantoio", "ulivi millenari"],
    imgKeywords: "olive,oil,italy,harvest,traditional",
  },
  {
    id: "alici-menaica-degustazione",
    titolo: "Le Alici di Menaica – Presidio Slow Food",
    categoria: "Gastronomia",
    luogo: "Pisciotta",
    comune: "Pisciotta",
    descrizione: "Presidio Slow Food e simbolo della tradizione cilentana, le alici di Menaica vengono pescate con una rete antichissima e maturate in terracotta con sale marino. Degustazione con il pescatore-produttore, visita alle 'menaiche' (le giare di terracotta), aperitivo cilentano con pane cafone e olio locale.",
    difficolta: "Facile",
    durata: "2 ore",
    prezzo: "Da €25/persona",
    inEvidenza: true,
    tags: ["alici di menaica", "slow food", "tradizione", "mare"],
    imgKeywords: "anchovies,fish,italy,traditional,slow food",
  },
  {
    id: "fico-bianco-cilento-dop",
    titolo: "Fico Bianco del Cilento DOP – Azienda Agricola",
    categoria: "Gastronomia",
    luogo: "Colline del Cilento",
    comune: "Pollica",
    descrizione: "Il Fico Bianco del Cilento è un presidio UNESCO della Dieta Mediterranea. Visita alle piante di fico centenarie, raccolta manuale, essiccazione tradizionale al sole e lavorazione artigianale dei fichi secchi farciti con mandorle, finocchietto e cioccolato. La stagione è agosto–settembre.",
    difficolta: "Facile",
    durata: "2 ore",
    prezzo: "Da €18/persona",
    tags: ["fico bianco", "dop", "dieta mediterranea", "artigianale"],
    imgKeywords: "fig,fruit,italy,traditional,organic",
  },
  {
    id: "cantine-vino-cilento-doc",
    titolo: "Tour Enologico – Vino DOC Cilento",
    categoria: "Gastronomia",
    luogo: "Cantine del Cilento",
    comune: "Agropoli",
    descrizione: "Il Cilento DOC comprende Aglianico, Fiano e Primitivo di straordinaria qualità. Tour nelle cantine storiche del territorio con degustazione di vini locali, visita alle vigne su terrazzamenti vista mare, abbinamento con salumi e formaggi cilentani. Alcune cantine sono condotte da giovani produttori che recuperano vitigni autoctoni.",
    difficolta: "Facile",
    durata: "3 ore",
    prezzo: "Da €30/persona",
    tags: ["vino", "doc", "cantina", "degustazione"],
    imgKeywords: "wine,vineyard,italy,tasting,cellar",
  },
  {
    id: "corso-cucina-cilentana",
    titolo: "Corso di Cucina Cilentana Tradizionale",
    categoria: "Gastronomia",
    luogo: "Agriturismi del Cilento",
    comune: "Vallo della Lucania",
    descrizione: "Impara i segreti della cucina cilentana: lagane e ceci, fusilli al ragù di capra, pane cafone, pastine con fagioli di Controne, scauratielli e mostaccioli. Il corso si tiene in agriturismo con prodotti dell'orto e dell'allevamento aziendale. Include pranzo con tutto quello che hai preparato.",
    difficolta: "Facile",
    durata: "4 ore",
    prezzo: "Da €65/persona",
    inEvidenza: true,
    tags: ["cucina tradizionale", "agriturismo", "lagane e ceci", "corso"],
    imgKeywords: "cooking,italy,traditional,pasta,food",
  },
  {
    id: "fagioli-controne-visita",
    titolo: "Fagioli di Controne – Presidio Slow Food",
    categoria: "Gastronomia",
    luogo: "Valle del Calore",
    comune: "Controne",
    descrizione: "I Fagioli di Controne sono un presidio Slow Food di straordinaria qualità: piccoli, cremosi, saporiti. Visita all'azienda agricola durante la raccolta (settembre–ottobre), degustazione della zuppa di fagioli con pane cafone e olio DOP Cilento, acquisto diretto dal produttore.",
    difficolta: "Facile",
    durata: "2 ore",
    prezzo: "Da €15/persona",
    tags: ["fagioli di controne", "slow food", "campagna", "produttore"],
    imgKeywords: "beans,legumes,italy,farm,organic",
  },
  {
    id: "carciofo-paestum-visita",
    titolo: "Carciofo Bianco di Pertosa e di Paestum",
    categoria: "Gastronomia",
    luogo: "Piana di Paestum",
    comune: "Capaccio-Paestum",
    descrizione: "Il carciofo bianco del Cilento e di Paestum è apprezzato in tutta Italia per la sua tenerezza e dolcezza. Visita ai campi durante la raccolta primaverile, incontro con i produttori, degustazione di carciofi crudi, fritti, in conserva e abbinati ai formaggi locali. Stagione: marzo–maggio.",
    difficolta: "Facile",
    durata: "2 ore",
    prezzo: "Da €15/persona",
    tags: ["carciofo", "paestum", "campagna", "primavera"],
    imgKeywords: "artichoke,vegetable,italy,farm,spring",
  },
  {
    id: "miele-cilento-apicoltura",
    titolo: "Miele del Parco Nazionale – Visita all'Apiario",
    categoria: "Gastronomia",
    luogo: "Boschi del Cilento",
    comune: "Rofrano",
    descrizione: "Il Cilento produce mieli di eccezionale varietà: castagno, millefiori, sulla, erica, corbezzolo. Visita guidata all'apiario con tuta apicola, estrazione del miele, degustazione di 5 qualità di miele con abbinamenti. Spiegazione del ciclo delle api e importanza dell'impollinazione nel Parco Nazionale.",
    difficolta: "Facile",
    durata: "2 ore",
    prezzo: "Da €20/persona",
    tags: ["miele", "api", "apiario", "bosco"],
    imgKeywords: "honey,beekeeper,italy,organic,natural",
  },
  {
    id: "birra-artigianale-cilento",
    titolo: "Birrificio Artigianale del Cilento",
    categoria: "Gastronomia",
    luogo: "Vallo della Lucania",
    comune: "Vallo della Lucania",
    descrizione: "Piccoli birrifici artigianali nati nel cuore del Cilento producono birre con ingredienti locali: fico bianco, limone, castagna, mirto. Visita guidata alla produzione, degustazione di 5 stili di birra con abbinamenti a salumi e formaggi tipici. Il movimento craft beer cilentano è in forte crescita.",
    difficolta: "Facile",
    durata: "2 ore",
    prezzo: "Da €25/persona",
    tags: ["birra artigianale", "craft beer", "degustazione", "produzione"],
    imgKeywords: "craft beer,brewery,italy,tasting,artisan",
  },
  {
    id: "dieta-mediterranea-pollica",
    titolo: "Esperienza Dieta Mediterranea – Pollica",
    categoria: "Gastronomia",
    luogo: "Pollica – Pioppi",
    comune: "Pollica",
    descrizione: "Pollica è la culla della Dieta Mediterranea, patrimonio UNESCO. Il Museo Living della Dieta Mediterranea di Pioppi e l'eredità di Ancel Keys sono il punto di partenza per un'esperienza autentica: visita al museo, pranzo tipico cilentano, passeggiata tra orti e pescatori locali.",
    difficolta: "Facile",
    durata: "3 ore",
    prezzo: "Da €35/persona",
    inEvidenza: true,
    linkEsterno: "https://dietamediterranea.com",
    tags: ["dieta mediterranea", "unesco", "ancel keys", "pollica"],
    imgKeywords: "mediterranean diet,italy,healthy,food,tradition",
  },

  // ── CULTURA ───────────────────────────────────────────────────────────────

  {
    id: "templi-paestum",
    titolo: "Templi Greci di Paestum – Patrimonio UNESCO",
    categoria: "Cultura",
    luogo: "Area Archeologica di Paestum",
    comune: "Capaccio-Paestum",
    descrizione: "I tre templi dorici di Paestum (VI–V sec. a.C.) sono tra i meglio conservati al mondo, vanto della Grande Grecia: il Tempio di Era I (Basilica), il Tempio di Poseidone ed il Tempio di Cerere. Il museo nazionale adiacente ospita la Tomba del Tuffatore, capolavoro della pittura greca.",
    difficolta: "Facile",
    durata: "3 ore",
    prezzo: "€12/persona",
    inEvidenza: true,
    linkEsterno: "https://www.museopaestum.beniculturali.it",
    tags: ["greci", "templi", "unesco", "museo", "storia"],
    imgKeywords: "greek temple,paestum,ruins,italy,ancient",
  },
  {
    id: "certosa-padula-unesco",
    titolo: "Certosa di San Lorenzo – Padula (UNESCO)",
    categoria: "Cultura",
    luogo: "Certosa di San Lorenzo",
    comune: "Padula",
    descrizione: "La Certosa di Padula è una delle più grandi certose d'Europa (51.500 mq) e Patrimonio UNESCO. Fondata nel 1306, ospita chiostri monumentali, il grande chiostro barocco con 84 colonne, la biblioteca e l'appartamento priore tra i più lussuosi del mondo monastico. Una meraviglia assoluta.",
    difficolta: "Facile",
    durata: "2,5 ore",
    prezzo: "€6/persona",
    inEvidenza: true,
    linkEsterno: "https://www.certosadipadula.it",
    tags: ["unesco", "certosa", "barocco", "monastero"],
    imgKeywords: "monastery,certosa,italy,baroque,cloister",
  },
  {
    id: "area-archeologica-velia",
    titolo: "Elea-Velia – Città dei Filosofi",
    categoria: "Cultura",
    luogo: "Area Archeologica di Velia",
    comune: "Ascea",
    descrizione: "Velia è la città di Parmenide e Zenone di Elea, dove nacque la scuola Eleatica (V sec. a.C.). L'area archeologica conserva la Porta Rosa (uno dei più antichi archi a tutto sesto d'Europa), l'acropoli, terme romane e interi quartieri della città greca. Un sito suggestivo e poco affollato.",
    difficolta: "Facile",
    durata: "2 ore",
    prezzo: "€5/persona",
    inEvidenza: true,
    tags: ["greci", "filosofia", "parmenide", "porta rosa"],
    imgKeywords: "archaeological,ruins,italy,greek,ancient",
  },
  {
    id: "castello-agropoli",
    titolo: "Castello Aragonese di Agropoli",
    categoria: "Cultura",
    luogo: "Borgo Antico di Agropoli",
    comune: "Agropoli",
    descrizione: "Il castello medievale di Agropoli domina sul promontorio con una vista eccezionale sul Golfo di Salerno e sui templi di Paestum. Fondato dai Bizantini nel VI sec., ampliato dagli Angioini e Aragonesi, ospita oggi mostre temporanee. Il borgo antico intorno è un gioiello di vicoli e panorami.",
    difficolta: "Facile",
    durata: "1,5 ore",
    prezzo: "Gratuito",
    tags: ["castello", "medievale", "borgo", "panorama"],
    imgKeywords: "castle,medieval,italy,village,sea view",
  },
  {
    id: "borgo-castellabate",
    titolo: "Borgo Medievale di Castellabate",
    categoria: "Cultura",
    luogo: "Centro Storico di Castellabate",
    comune: "Castellabate",
    descrizione: "Castellabate è uno dei Borghi più Belli d'Italia: un gioiello medievale arroccato su un colle a 280 m sul mare. Fondato nel XII sec. dal Monaco Costabile, è famoso per i vicoli in pietra, i belvederi con vista sulle isole Li Galli e Capri, la collegiata e il castello normanno.",
    difficolta: "Facile",
    durata: "2 ore",
    prezzo: "Gratuito",
    inEvidenza: true,
    tags: ["borgo medievale", "belvedere", "pietra", "panorama"],
    imgKeywords: "medieval village,italy,hilltop,stone,panorama",
  },
  {
    id: "museo-nazionale-paestum",
    titolo: "Museo Nazionale di Paestum – La Tomba del Tuffatore",
    categoria: "Cultura",
    luogo: "Museo Nazionale di Paestum",
    comune: "Capaccio-Paestum",
    descrizione: "Il museo custodisce la Tomba del Tuffatore (480 a.C.), unico esempio di pittura figurativa greca del periodo classico in Italia. Le cinque lastre dipinte rappresentano un banchetto simposiale e la celebre figura del tuffatore, simbolo dell'anima che si tuffa nell'aldilà.",
    difficolta: "Facile",
    durata: "2 ore",
    prezzo: "€12 (incluso nell'ingresso area)",
    inEvidenza: true,
    tags: ["tomba del tuffatore", "pittura greca", "museo", "capolavoro"],
    imgKeywords: "museum,ancient,fresco,italy,greek art",
  },
  {
    id: "santuario-gelbison",
    titolo: "Santuario di Santa Maria del Gelbison",
    categoria: "Cultura",
    luogo: "Monte Gelbison – 1.705 m",
    comune: "Novi Velia",
    descrizione: "Il Santuario della Madonna di Novi Velia, in vetta al Monte Gelbison, è uno dei luoghi di pellegrinaggio più importanti del Sud Italia. La salita a piedi è un percorso spirituale, ma è accessibile anche in auto. La vista panoramica abbraccia tutto il Cilento e il Golfo di Policastro.",
    difficolta: "Facile",
    durata: "2 ore",
    prezzo: "Gratuito",
    tags: ["santuario", "pellegrinaggio", "religioso", "panorama"],
    imgKeywords: "sanctuary,mountain,italy,pilgrimage,panorama",
  },
  {
    id: "centro-storico-teggiano",
    titolo: "Teggiano – La Piccola Roma del Cilento",
    categoria: "Cultura",
    luogo: "Centro Storico di Teggiano",
    comune: "Teggiano",
    descrizione: "Teggiano, l'antica Diano, è uno scrigno d'arte e storia: il Duomo di Santa Maria Maggiore (XIII sec.), il Castello Macchiaroli (XII sec.), ben 16 chiese storiche, musei civici e gallerie d'arte. Il centro storico interamente medievale è rimasto intatto nei secoli.",
    difficolta: "Facile",
    durata: "3 ore",
    prezzo: "Gratuito",
    tags: ["medievale", "duomo", "castello", "arte"],
    imgKeywords: "italy,medieval,church,history,village",
  },
  {
    id: "roccagloriosa-scavi",
    titolo: "Scavi Archeologici di Roccagloriosa",
    categoria: "Cultura",
    luogo: "Area Archeologica di Roccagloriosa",
    comune: "Roccagloriosa",
    descrizione: "Il sito lucano di Roccagloriosa (IV–III sec. a.C.) è una delle più importanti testimonianze delle popolazioni preromane del Cilento. Gli scavi hanno portato alla luce abitazioni, necropoli e oggetti di straordinaria qualità. Visita guidata con archeologi.",
    difficolta: "Facile",
    durata: "2 ore",
    prezzo: "Da €5/persona",
    tags: ["lucani", "preromano", "scavi", "archeologia"],
    imgKeywords: "excavation,archaeology,italy,ancient,ruins",
  },
  {
    id: "centro-storico-sala-consilina",
    titolo: "Sala Consilina – Porta del Vallo di Diano",
    categoria: "Cultura",
    luogo: "Centro Storico di Sala Consilina",
    comune: "Sala Consilina",
    descrizione: "Sala Consilina è la capitale culturale del Vallo di Diano, con un centro storico di palazzi nobiliari, chiese barocche e il Museo Archeologico che custodisce reperti dell'Età del Ferro della civiltà villanoviana. Da non perdere la Fiera di San Sisto, una delle più antiche del Sud.",
    difficolta: "Facile",
    durata: "2 ore",
    prezzo: "Gratuito",
    tags: ["vallo di diano", "barocco", "museo", "storia"],
    imgKeywords: "italy,town,history,baroque,southern",
  },

  // ── SPORT ─────────────────────────────────────────────────────────────────

  {
    id: "mountain-bike-parco-cilento",
    titolo: "Mountain Bike nel Parco Nazionale del Cilento",
    categoria: "Sport",
    luogo: "Parco Nazionale del Cilento",
    comune: "Vallo della Lucania",
    descrizione: "Itinerari di mountain bike per tutti i livelli nel Parco Nazionale: dalle ciclabili sul fondovalle Calore alle salite impegnative verso i boschi di alta quota. Guide locali certificate portano i ciclisti sui percorsi più belli, con noleggio E-bike disponibile per chi vuole faticare meno.",
    difficolta: "Media",
    durata: "4–6 ore",
    prezzo: "Da €30/persona",
    inEvidenza: true,
    tags: ["mountain bike", "e-bike", "parco", "natura"],
    imgKeywords: "mountain bike,trail,italy,nature,cycling",
  },
  {
    id: "arrampicata-palinuro",
    titolo: "Arrampicata sulle Falesie di Palinuro",
    categoria: "Sport",
    luogo: "Falesie di Capo Palinuro",
    comune: "Centola",
    descrizione: "Le falesie calcaree di Palinuro offrono vie di arrampicata per ogni livello: dalla falesia per principianti a strapiombi sul mare per esperti. Un sito unico in Italia dove si scala con il Mediterraneo ai piedi. Guide UIAGM con materiale incluso. Periodo migliore: primavera e autunno.",
    difficolta: "Difficile",
    durata: "4 ore",
    prezzo: "Da €50/persona",
    tags: ["arrampicata", "falesia", "mare", "roccia"],
    imgKeywords: "climbing,rock,italy,cliff,sea",
  },
  {
    id: "canyoning-gole-calore",
    titolo: "Canyoning nelle Gole del Calore",
    categoria: "Sport",
    luogo: "Gole del Calore Lucano",
    comune: "Felitto",
    descrizione: "Discesa delle Gole del Calore in canyoning: salti nelle pozze, tobogan naturali su roccia levigata, calate in corda nel canyon. Un'avventura adrenalinica in un contesto naturale di rara bellezza. Guide esperte, attrezzatura completa fornita (muta, casco, imbragatura).",
    difficolta: "Media",
    durata: "4–5 ore",
    prezzo: "Da €55/persona",
    inEvidenza: true,
    tags: ["canyoning", "canyon", "avventura", "acqua"],
    imgKeywords: "canyoning,canyon,adventure,italy,water",
  },
  {
    id: "parapendio-monte-stella",
    titolo: "Parapendio Biposto da Monte Stella",
    categoria: "Sport",
    luogo: "Monte Stella",
    comune: "Santa Marina",
    descrizione: "Vola in biposto con un istruttore qualificato dal Monte Stella con vista sul Golfo di Policastro e la costa cilentana. Nessuna esperienza necessaria, si decolla insieme all'istruttore. Un'emozione indimenticabile tra cielo e mare. Disponibile su prenotazione con vento favorevole.",
    difficolta: "Facile",
    durata: "1 ora (volo 20 min.)",
    prezzo: "Da €80/persona",
    tags: ["parapendio", "biposto", "volo", "adrenalina"],
    imgKeywords: "paragliding,flight,italy,coast,sky",
  },
  {
    id: "equitazione-costa-cilento",
    titolo: "Equitazione lungo la Costa Cilentana",
    categoria: "Sport",
    luogo: "Maneggi costieri del Cilento",
    comune: "Agropoli",
    descrizione: "Passeggiata a cavallo lungo la costa del Cilento: attraverso pinete, macchia mediterranea e spiagge poco frequentate. Maneggi attrezzati con istruttori FEI per principianti e cavalieri esperti. Tour al tramonto sulla spiaggia: un'esperienza romantica e indimenticabile.",
    difficolta: "Facile",
    durata: "2–3 ore",
    prezzo: "Da €40/persona",
    tags: ["equitazione", "cavalli", "spiaggia", "tramonto"],
    imgKeywords: "horse riding,coast,italy,sunset,beach",
  },
  {
    id: "canyoning-rio-sammaro",
    titolo: "Canyoning sul Rio Sammaro",
    categoria: "Sport",
    luogo: "Rio Sammaro",
    comune: "Sacco",
    descrizione: "Il Rio Sammaro è uno dei canyon più spettacolari del Parco Nazionale del Cilento. La discesa combina salti nell'acqua, traversate di pozze profonde e forre strette in un ambiente di assoluta wilderness. Percorso avanzato, con attrezzatura completa fornita.",
    difficolta: "Difficile",
    durata: "6 ore",
    prezzo: "Da €70/persona",
    tags: ["canyoning", "avanzato", "rio sammaro", "selvatico"],
    imgKeywords: "canyon,river,gorge,adventure,sport",
  },
  {
    id: "via-ferrata-palinuro",
    titolo: "Via Ferrata al Capo Palinuro",
    categoria: "Sport",
    luogo: "Capo Palinuro",
    comune: "Centola",
    descrizione: "Una via ferrata sul promontorio di Palinuro permette di esplorare pareti rocciose a picco sul mare inaccessibili a piedi. Il percorso attrezzato con cavi e staffe è adatto a chi ha esperienza minima di arrampicata. Viste mozzafiato sulle grotte marine dall'alto.",
    difficolta: "Media",
    durata: "3 ore",
    prezzo: "Da €45/persona",
    tags: ["via ferrata", "roccia", "altezza", "panorama marino"],
    imgKeywords: "via ferrata,climbing,coast,italy,adventure",
  },
  {
    id: "orienteering-parco",
    titolo: "Orienteering nel Parco Nazionale",
    categoria: "Sport",
    luogo: "Parco Nazionale del Cilento",
    comune: "Castellabate",
    descrizione: "L'orienteering nel Parco Nazionale del Cilento combina sport, natura e sfida intellettuale: trovare una serie di punti nascosti nel bosco usando solo mappa e bussola. Ideale per famiglie e gruppi, con percorsi adatti a ogni età e livello fisico. Un'attività che avvicina i ragazzi alla natura.",
    difficolta: "Facile",
    durata: "2–3 ore",
    prezzo: "Da €15/persona",
    tags: ["orienteering", "mappa", "bosco", "famiglie"],
    imgKeywords: "orienteering,map,forest,sport,italy",
  },

  // ── BENESSERE ─────────────────────────────────────────────────────────────

  {
    id: "terme-contursi",
    titolo: "Terme di Contursi Terme",
    categoria: "Benessere",
    luogo: "Stabilimenti Termali di Contursi",
    comune: "Contursi Terme",
    descrizione: "Le acque sulfuree e bicarbonato-alcaline di Contursi Terme sgorgano a 38°C e sono indicate per patologie reumatologiche, respiratorie e dermatologiche. Gli stabilimenti moderni offrono piscine termali, fanghi, inalazioni e un'ampia gamma di trattamenti wellness. Convenzioni SSN disponibili.",
    difficolta: "Facile",
    durata: "Giornata intera",
    prezzo: "Da €25/persona",
    inEvidenza: true,
    linkEsterno: "https://www.termecontursi.com",
    tags: ["terme", "salute", "acque termali", "relax"],
    imgKeywords: "thermal spa,hot spring,italy,wellness,relax",
  },
  {
    id: "terme-montesano",
    titolo: "Terme di Montesano sulla Marcellana",
    categoria: "Benessere",
    luogo: "Stabilimento Termale",
    comune: "Montesano sulla Marcellana",
    descrizione: "Le terme di Montesano sulla Marcellana sorgono nell'alta Valle del Noce, al confine con la Basilicata. Acque solfato-alcaline fredde e calde per cure termali, thalassoterapia e percorsi benessere immersi nel verde dei boschi del Cilento interno. Una dimensione di totale tranquillità.",
    difficolta: "Facile",
    durata: "4 ore",
    prezzo: "Da €20/persona",
    tags: ["terme", "acqua sulfurea", "vallo di diano", "relax"],
    imgKeywords: "thermal bath,wellness,italy,spa,nature",
  },
  {
    id: "yoga-spiaggia-castellabate",
    titolo: "Yoga all'Alba sulla Spiaggia",
    categoria: "Benessere",
    luogo: "Spiagge di Castellabate",
    comune: "Castellabate",
    descrizione: "Lezioni di yoga e meditazione all'alba sulla spiaggia, con il suono del mare e i colori del sole nascente. Insegnanti certificati propongono sessioni di hatha yoga, yin yoga e yoga del respiro. Disponibile anche yoga al tramonto con aperitivo rilassante finale.",
    difficolta: "Facile",
    durata: "1,5 ore",
    prezzo: "Da €20/sessione",
    tags: ["yoga", "alba", "spiaggia", "meditazione"],
    imgKeywords: "yoga,beach,italy,sunrise,meditation",
  },
  {
    id: "meditazione-bosco-cervati",
    titolo: "Meditazione e Forest Bathing nel Bosco",
    categoria: "Benessere",
    luogo: "Boschi del Monte Cervati",
    comune: "Sanza",
    descrizione: "Il forest bathing (shinrin-yoku) consiste nell'immergersi lentamente nel bosco, attivando tutti i sensi. Guide specializzate conducono sessioni di 3 ore tra le faggete del Cervati, con esercizi di mindfulness, respirazione e meditazione camminata. Benefici scientificamente provati per il benessere psicofisico.",
    difficolta: "Facile",
    durata: "3 ore",
    prezzo: "Da €35/persona",
    tags: ["forest bathing", "meditazione", "mindfulness", "bosco"],
    imgKeywords: "forest bathing,meditation,forest,italy,mindfulness",
  },
  {
    id: "ritiro-benessere-agriturismo",
    titolo: "Weekend Benessere in Agriturismo Cilentano",
    categoria: "Benessere",
    luogo: "Agriturismi del Cilento",
    comune: "Vallo della Lucania",
    descrizione: "Weekend di benessere completo in agriturismo biologico: yoga mattutino, massaggi con olio d'oliva DOP Cilento, trattamenti viso con argille locali, bagni nell'uliveto al tramonto. Cucina genuina con prodotti dell'orto, vino biologico, nessun telefono. Un vero detox dal quotidiano.",
    difficolta: "Facile",
    durata: "2 giorni",
    prezzo: "Da €180/persona",
    inEvidenza: true,
    tags: ["agriturismo", "weekend", "massaggio", "detox"],
    imgKeywords: "agriturismo,wellness,italy,olive,countryside",
  },
  {
    id: "massaggi-olio-dop",
    titolo: "Massaggio Tradizionale con Olio DOP Cilento",
    categoria: "Benessere",
    luogo: "Centri Benessere del Cilento",
    comune: "Agropoli",
    descrizione: "Il massaggio con l'olio extravergine d'oliva DOP Cilento è una pratica tradizionale della cultura contadina locale. Centri benessere e spa propongono trattamenti corpo completi con olio appena franto, argille vulcaniche dei Campi Flegrei e erbe officinali del Parco Nazionale.",
    difficolta: "Facile",
    durata: "1,5 ore",
    prezzo: "Da €70/persona",
    tags: ["massaggio", "olio d'oliva", "spa", "benessere"],
    imgKeywords: "massage,oil,wellness,italy,relax",
  },
  {
    id: "bagni-termali-polla",
    titolo: "Grotta delle Meraviglie – Bagni Termali di Polla",
    categoria: "Benessere",
    luogo: "Valle del Tanagro",
    comune: "Polla",
    descrizione: "Le sorgenti termali della Valle del Tanagro, conosciute sin dall'antichità, offrono acque a temperatura costante di 34°C ricche di sali minerali. La piccola struttura termale di Polla, immersa nel verde del Parco Nazionale, è un rifugio di pace autentica.",
    difficolta: "Facile",
    durata: "2 ore",
    prezzo: "Da €15/persona",
    tags: ["terme", "grotta", "vallo di diano", "acqua"],
    imgKeywords: "thermal,grotto,italy,water,relaxation",
  },

  // ── ARTIGIANATO ───────────────────────────────────────────────────────────

  {
    id: "ceramica-capaccio",
    titolo: "Laboratorio di Ceramica Tradizionale",
    categoria: "Artigianato",
    luogo: "Laboratori Artigiani del Cilento",
    comune: "Capaccio-Paestum",
    descrizione: "La ceramica locale si ispira ai motivi greci dei Templi di Paestum e alla tradizione contadina cilentana. Nel laboratorio artigianale crei il tuo oggetto unico al tornio o a mano libera, con l'argilla locale. Il maestro ceramista insegna le tecniche tradizionali di decorazione e cottura.",
    difficolta: "Facile",
    durata: "3 ore",
    prezzo: "Da €40/persona",
    tags: ["ceramica", "tornio", "argilla", "tradizione"],
    imgKeywords: "pottery,clay,italy,craft,artisan",
  },
  {
    id: "tessitura-episcopia",
    titolo: "Tessitura Tradizionale – Telaio a Mano",
    categoria: "Artigianato",
    luogo: "Botteghe artigiane",
    comune: "Teggiano",
    descrizione: "La tessitura al telaio a mano è una tradizione secolare del Vallo di Diano. Le artigiane tramandano i pattern tradizionali: coperte di lana, tovagliati di lino, stuoie di giunchi. Laboratorio partecipativo: impara a usare il telaio e crea un piccolo manufatto da portare a casa.",
    difficolta: "Facile",
    durata: "2,5 ore",
    prezzo: "Da €30/persona",
    tags: ["tessitura", "telaio", "lana", "tradizione"],
    imgKeywords: "weaving,loom,italy,traditional,textile",
  },
  {
    id: "coltelleria-pattano",
    titolo: "Coltelleria Artigianale di Pattano",
    categoria: "Artigianato",
    luogo: "Pattano",
    comune: "Vallo della Lucania",
    descrizione: "Pattano è famosa per la lavorazione artigianale dei coltelli da pastore, tradizione secolare tramandata di padre in figlio. Visita alla bottega del maestro coltellnaio, dimostrazione della forgiatura e lucidatura delle lame, possibilità di creare il manico in corno o ulivo.",
    difficolta: "Facile",
    durata: "2 ore",
    prezzo: "Da €25/persona",
    inEvidenza: true,
    tags: ["coltelli", "forgiatura", "maestro artigiano", "tradizione"],
    imgKeywords: "knife,blacksmith,italy,craft,traditional",
  },
  {
    id: "lavorazione-ulivo",
    titolo: "Intaglio del Legno d'Ulivo",
    categoria: "Artigianato",
    luogo: "Botteghe Artigiane",
    comune: "Pisciotta",
    descrizione: "L'ulivo secolare del Cilento, con le sue venature scure e chiare, è il materiale ideale per oggetti unici: taglieri, ciotole, posate, sculture. Il maestro intagliatore insegna le tecniche base di tornitura e scultura del legno. Ogni oggetto è un pezzo unico, plasmato da un albero che può avere mille anni.",
    difficolta: "Facile",
    durata: "3 ore",
    prezzo: "Da €35/persona",
    tags: ["legno d'ulivo", "intaglio", "tornio", "scultura"],
    imgKeywords: "wood carving,olive wood,italy,craft,artisan",
  },
  {
    id: "cesteria-vimini",
    titolo: "Cesteria con Vimini e Giunchi",
    categoria: "Artigianato",
    luogo: "Colline cilentane",
    comune: "Ascea",
    descrizione: "La cesteria è una delle arti più antiche del Cilento, un tempo essenziale per l'economia contadina. Le ultime artigiane tramandano la tecnica di intreccio del vimini e del giunco raccolto lungo i fiumi. Laboratorio di 3 ore per creare un cestino o sottopentola intrecciato a mano.",
    difficolta: "Facile",
    durata: "3 ore",
    prezzo: "Da €25/persona",
    tags: ["cesteria", "vimini", "giunco", "intrecciato"],
    imgKeywords: "basket weaving,wicker,italy,craft,traditional",
  },
  {
    id: "produzione-pasta-fresca",
    titolo: "Laboratorio di Pasta Fresca Cilentana",
    categoria: "Artigianato",
    luogo: "Agriturismi del Cilento",
    comune: "Vallo della Lucania",
    descrizione: "I fusilli cilentani si fanno avvolgendo la pasta attorno a un ferro, una tecnica che richiede destrezza e pazienza. Laboratorio con la nonna del borgo: impari a fare fusilli, lagane, maltagliati e scialatielli, usando solo farina di grano duro locale, acqua e sale. Pranzo finale con quanto prodotto.",
    difficolta: "Facile",
    durata: "3 ore",
    prezzo: "Da €45/persona",
    tags: ["pasta fresca", "fusilli", "nonna", "tradizione"],
    imgKeywords: "pasta making,italy,traditional,handmade,food",
  },
  {
    id: "laboratorio-miele-artigianale",
    titolo: "Lavorazione Artigianale del Miele",
    categoria: "Artigianato",
    luogo: "Apiario del Cilento",
    comune: "Rofrano",
    descrizione: "Accompagna l'apicoltore durante l'estrazione del miele: smielatura centrifuga, filtraggio, invasettamento e etichettatura. Ogni momento è spiegato con cura, con tuta protettiva fornita. Alla fine, assaggi 5 varietà di miele e porti a casa un vasetto della tua produzione.",
    difficolta: "Facile",
    durata: "2,5 ore",
    prezzo: "Da €30/persona",
    tags: ["miele", "api", "smielatura", "laboratorio"],
    imgKeywords: "honey,beekeeper,extraction,italy,artisan",
  },
  {
    id: "ricamo-ricette-tradizionali",
    titolo: "Ricamo Tradizionale Cilentano",
    categoria: "Artigianato",
    luogo: "Associazioni culturali del Cilento",
    comune: "Castellabate",
    descrizione: "Il punto croce e il ricamo a rammendo sono tradizioni vive nel Cilento, con motivi floreali, paesaggi costieri e soggetti della vita contadina. Maestre ricamatrici insegnano le basi del ricamo su tela di lino, con disegni tradizionali cilentani. Adatto anche per principianti assoluti.",
    difficolta: "Facile",
    durata: "2 ore",
    prezzo: "Da €20/persona",
    tags: ["ricamo", "punto croce", "tessile", "tradizione"],
    imgKeywords: "embroidery,needlework,italy,traditional,craft",
  },
];

export function getInEvidenza(): Esperienza[] {
  return esperienze.filter((e) => e.inEvidenza);
}
