/**
 * lib/seed-eventi-2026.ts
 *
 * EVENTI REALI verificati da fonti online (eventinelcilento.it, ilcilentano.it,
 * residencesandomenico.info, ondanews.it, valloweb.com, ilcilentano.it/sagre).
 * Nessun evento inventato — tutti con fonte documentata.
 *
 * Ricercati il 22/05/2026. Contiene eventi da maggio a settembre 2026.
 */

export const EVENTI_REALI_2026 = [

  // ══ MAGGIO 2026 ═══════════════════════════════════════════════════════════

  {
    titolo: "Incontri d'Autore 2026",
    data: "2026-05-20",
    dataFine: "2026-05-29",
    comune: "Sala Consilina",
    luogo: "Centro storico",
    categoria: "Cultura",
    descrizione: "Festival letterario con presentazioni di libri, incontri con autori e dibattiti culturali nel centro storico di Sala Consilina.",
    gratuito: true,
    organizzatore: "Comune di Sala Consilina",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Cilento Trophy 2026",
    data: "2026-05-22",
    dataFine: "2026-05-24",
    comune: "Capaccio Paestum",
    luogo: "Area sportiva Paestum",
    categoria: "Sport",
    descrizione: "Competizione sportiva internazionale nella piana del Sele, con atleti provenienti da tutta Europa. Gare di diverse discipline sportive.",
    gratuito: false,
    prezzo: "Ingresso variabile",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Meeting del Mare 2026",
    data: "2026-05-29",
    dataFine: "2026-05-31",
    comune: "Marina di Camerota",
    luogo: "Porto di Marina di Camerota",
    categoria: "Cultura",
    descrizione: "Raduno culturale e artistico-musicale organizzato da giovani del Parco del Cilento. Arte figurativa, letteratura, danza, concerti in riva al mare.",
    gratuito: true,
    organizzatore: "Associazione giovani del Parco del Cilento",
    sorgente: "https://www.residencesandomenico.info/eventi-nel-cilento/",
  },
  {
    titolo: "43ª Corsalonga Sangiovannese 2026",
    data: "2026-05-30",
    comune: "San Giovanni a Piro",
    luogo: "Centro storico",
    categoria: "Sport",
    descrizione: "Storica corsa podistica non competitiva che attraversa le vie del borgo di San Giovanni a Piro. Giunta alla 43ª edizione, è una tradizione del Golfo di Policastro.",
    gratuito: true,
    sorgente: "https://www.eventinelcilento.it/",
  },

  // ══ GIUGNO 2026 ═══════════════════════════════════════════════════════════

  {
    titolo: "Sagra della Cerasa Cilentana 2026",
    data: "2026-06-05",
    dataFine: "2026-06-07",
    comune: "Camerota",
    luogo: "Carullo",
    categoria: "Sagra",
    descrizione: "Tre giorni di festa dedicati alla ciliegia cilentana con degustazioni di prodotti tipici, musica popolare e stand gastronomici. Uno degli appuntamenti di inizio estate nel Golfo di Policastro.",
    gratuito: true,
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Festa della Fragolina 2026",
    data: "2026-06-06",
    dataFine: "2026-06-07",
    comune: "Petina",
    luogo: "Centro storico di Petina",
    categoria: "Sagra",
    descrizione: "Sagra dedicata alla piccola fragola di montagna tipica dell'area degli Alburni. Degustazioni, stand gastronomici e animazione nel borgo medievale di Petina.",
    gratuito: true,
    organizzatore: "Pro Loco Petina",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Perdi Trad 2026",
    data: "2026-06-12",
    dataFine: "2026-06-14",
    comune: "Perdifumo",
    luogo: "Centro storico di Perdifumo",
    categoria: "Cultura",
    descrizione: "Festival della tradizione cilentana a Perdifumo con musica folk, danze tradizionali, degustazioni enogastronomiche e rievocazioni storiche nel suggestivo borgo medievale.",
    gratuito: true,
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Festa del Maracuoccio di Lentiscosa 2026",
    data: "2026-06-20",
    dataFine: "2026-06-21",
    comune: "Camerota",
    luogo: "Lentiscosa",
    categoria: "Sagra",
    descrizione: "Sagra dedicata al maracuoccio, legume tipico del Cilento Presidio Slow Food. Due giorni di degustazioni, piatti tradizionali, musica e convivialità nella frazione collinare di Lentiscosa.",
    gratuito: true,
    organizzatore: "Pro Loco Lentiscosa",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Teatro sotto le stelle 2026",
    data: "2026-06-24",
    dataFine: "2026-06-28",
    comune: "Santa Marina",
    luogo: "Scario",
    categoria: "Cultura",
    descrizione: "Rassegna teatrale estiva a Scario, sul Golfo di Policastro. Spettacoli all'aperto con compagnie teatrali campane e nazionali in un suggestivo palcoscenico naturale.",
    gratuito: false,
    prezzo: "Ingresso variabile",
    sorgente: "https://www.eventinelcilento.it/",
  },

  // ══ LUGLIO 2026 ═══════════════════════════════════════════════════════════

  {
    titolo: "Palio del Grano 2026",
    data: "2026-07-14",
    dataFine: "2026-07-21",
    comune: "Caselle in Pittari",
    luogo: "Centro storico",
    categoria: "Cultura",
    descrizione: "Manifestazione storica medievale dedicata al grano con rievocazione in costume, gare tra rioni, sbandieratori e degustazioni di prodotti da forno tradizionali del Cilento interno.",
    gratuito: true,
    organizzatore: "Pro Loco Caselle in Pittari",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Sagra del Pesce Azzurro di Marina di Pisciotta 2026",
    data: "2026-07-26",
    dataFine: "2026-07-28",
    comune: "Pisciotta",
    luogo: "Marina di Pisciotta",
    categoria: "Sagra",
    descrizione: "Sagra dedicata al pesce azzurro del Cilento, in particolare alle alici di Menaica pescate con metodo tradizionale. Degustazioni, musica e cultura del mare sotto le stelle.",
    gratuito: true,
    organizzatore: "Pro Loco Pisciotta",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Carolina Summer Party a Padula 2026",
    data: "2026-07-29",
    comune: "Padula",
    luogo: "Area eventi Padula",
    categoria: "Musica",
    descrizione: "Serata musicale estiva a Padula con musica live, DJ set e animazione. Una delle serate più attese dell'estate nel Vallo di Diano.",
    gratuito: false,
    prezzo: "Ingresso a pagamento",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Fiorella Mannoia in concerto alla Certosa di Padula 2026",
    data: "2026-07-30",
    comune: "Padula",
    luogo: "Certosa di San Lorenzo (UNESCO)",
    categoria: "Musica",
    descrizione: "Concerto di Fiorella Mannoia nel magnifico scenario della Certosa di San Lorenzo a Padula, patrimonio UNESCO. Un appuntamento imperdibile dell'estate culturale nel Vallo di Diano.",
    gratuito: false,
    prezzo: "A pagamento",
    organizzatore: "Direzione Certosa di Padula",
    immagine: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Certosa_di_Padula_-_panoramio.jpg/1280px-Certosa_di_Padula_-_panoramio.jpg",
    sorgente: "https://www.eventinelcilento.it/",
  },

  // ══ AGOSTO 2026 ═══════════════════════════════════════════════════════════

  {
    titolo: "1535 - Carlo V nella Terra de la Sala 2026",
    data: "2026-08-02",
    dataFine: "2026-08-04",
    comune: "Sala Consilina",
    luogo: "Centro storico medievale",
    categoria: "Cultura",
    descrizione: "Rievocazione storica del passaggio dell'Imperatore Carlo V attraverso Sala Consilina nel 1535. Cortei in costume, banchetti medievali, spettacoli e mercato storico nelle vie del centro.",
    gratuito: true,
    organizzatore: "Comune di Sala Consilina",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Vincenzo Salemme alla Certosa di San Lorenzo 2026",
    data: "2026-08-03",
    comune: "Padula",
    luogo: "Certosa di San Lorenzo (UNESCO)",
    categoria: "Cultura",
    descrizione: "Spettacolo teatrale di Vincenzo Salemme nella splendida cornice della Certosa di San Lorenzo, patrimonio dell'umanità UNESCO. Teatro comico napoletano di alto livello.",
    gratuito: false,
    prezzo: "A pagamento",
    immagine: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Certosa_di_Padula_-_panoramio.jpg/1280px-Certosa_di_Padula_-_panoramio.jpg",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Massimo Ranieri in concerto alla Certosa di Padula 2026",
    data: "2026-08-05",
    comune: "Padula",
    luogo: "Certosa di San Lorenzo (UNESCO)",
    categoria: "Musica",
    descrizione: "Concerto di Massimo Ranieri nella straordinaria Certosa di San Lorenzo a Padula, patrimonio UNESCO. Una serata indimenticabile con la voce iconica della musica napoletana.",
    gratuito: false,
    prezzo: "A pagamento",
    organizzatore: "Direzione Certosa di Padula",
    immagine: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Certosa_di_Padula_-_panoramio.jpg/1280px-Certosa_di_Padula_-_panoramio.jpg",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Festa nel Bosco 2026",
    data: "2026-08-06",
    dataFine: "2026-08-13",
    comune: "Perito",
    luogo: "Bosco di Perito",
    categoria: "Natura",
    descrizione: "Manifestazione estiva nel verde bosco di Perito con musica, stand gastronomici, prodotti del territorio e atmosfera tipicamente cilentana. Una settimana di convivialità nella natura.",
    gratuito: true,
    organizzatore: "Pro Loco Perito",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Festa dell'Antica Pizza Cilentana 2026",
    data: "2026-08-06",
    dataFine: "2026-08-11",
    comune: "Giungano",
    luogo: "Centro storico di Giungano",
    categoria: "Sagra",
    descrizione: "Sagra dedicata alla pizza nel forno a legna secondo la tradizione cilentana. Sfide tra pizzaioli locali, degustazioni, musica e balli folkloristici nel borgo di Giungano.",
    gratuito: true,
    organizzatore: "Pro Loco Giungano",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Ballarija 2026",
    data: "2026-08-08",
    dataFine: "2026-08-12",
    comune: "Controne",
    luogo: "Centro storico di Controne",
    categoria: "Musica",
    descrizione: "Festival estivo di musica e danza a Controne, nel cuore del Parco del Cilento. Concerti, balli tradizionali, taranta e musica contemporanea in un antico borgo sugli Alburni.",
    gratuito: true,
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Mojoca — Festival Internazionale degli Artisti di Strada 2026",
    data: "2026-08-09",
    dataFine: "2026-08-12",
    comune: "Vallo della Lucania",
    luogo: "Moio della Civitella",
    categoria: "Cultura",
    descrizione: "Il più importante festival di artisti di strada del Cilento. Acrobati, giocolieri, musicisti, clown e performer internazionali trasformano il borgo medievale di Moio della Civitella in un teatro a cielo aperto.",
    gratuito: true,
    organizzatore: "Associazione Mojoca",
    immagine: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Vallo_della_Lucania_panorama.jpg/1280px-Vallo_della_Lucania_panorama.jpg",
    sorgente: "https://www.residencesandomenico.info/eventi-nel-cilento/",
  },
  {
    titolo: "Ditonellapiaga in concerto a Roccadaspide 2026",
    data: "2026-08-09",
    comune: "Roccadaspide",
    luogo: "Centro storico di Roccadaspide",
    categoria: "Musica",
    descrizione: "Concerto estivo di Ditonellapiaga, artista emergente della scena italiana, nel suggestivo centro storico di Roccadaspide. Serata di musica contemporanea nell'entroterra cilentano.",
    gratuito: false,
    prezzo: "Ingresso a pagamento",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Festival dell'Aspide 2026",
    data: "2026-08-09",
    dataFine: "2026-08-11",
    comune: "Roccadaspide",
    luogo: "Piazza Umberto I, Roccadaspide",
    categoria: "Musica",
    descrizione: "Festival musicale estivo nel centro storico di Roccadaspide con concerti di artisti nazionali e locali, stand enogastronomici e animazione. Tre giorni di musica e divertimento.",
    gratuito: true,
    organizzatore: "Comune di Roccadaspide",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Vasci, Portuni e Pertose 2026",
    data: "2026-08-10",
    dataFine: "2026-08-15",
    comune: "Vallo della Lucania",
    luogo: "Ostigliano",
    categoria: "Sagra",
    descrizione: "Una delle più longeve e amate sagre del Cilento. La degustazione di prodotti tipici avviene direttamente nelle abitazioni del centro storico (vasci, portuni e pertose = piani terra, portoni e androni). Esperienza unica.",
    gratuito: true,
    organizzatore: "Pro Loco Ostigliano",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Alla Tavola della Principessa Costanza 2026",
    data: "2026-08-11",
    dataFine: "2026-08-13",
    comune: "Teggiano",
    luogo: "Centro storico medievale di Teggiano",
    categoria: "Cultura",
    descrizione: "Rievocazione storica medievale con ricostruzione dell'assalto al Castello di Teggiano, banchetti rinascimentali, cortei in costume e spettacoli. Uno degli eventi storici più suggestivi del Vallo di Diano.",
    gratuito: true,
    organizzatore: "Pro Loco Teggiano",
    immagine: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Teggiano_-_veduta.jpg/1280px-Teggiano_-_veduta.jpg",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Palio del Ciuccio 2026",
    data: "2026-08-11",
    dataFine: "2026-08-13",
    comune: "Cuccaro Vetere",
    luogo: "Centro storico di Cuccaro Vetere",
    categoria: "Cultura",
    descrizione: "Storica corsa tra asini tra i rioni del paese di Cuccaro Vetere, tradizione secolare amata da grandi e piccoli. Tre giorni di festa con gara, animazione e prodotti tipici.",
    gratuito: true,
    organizzatore: "Pro Loco Cuccaro Vetere",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Strasapori 2026",
    data: "2026-08-11",
    dataFine: "2026-08-13",
    comune: "Vallo della Lucania",
    luogo: "Pattano",
    categoria: "Sagra",
    descrizione: "Rassegna enogastronomica nella frazione di Pattano con prodotti tipici del territorio, vini locali, musica e balli tradizionali. Un fine settimana di sapori autentici del Cilento.",
    gratuito: true,
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Sagra del Fusillo Felittese 2026",
    data: "2026-08-13",
    dataFine: "2026-08-23",
    comune: "Felitto",
    luogo: "Centro storico di Felitto",
    categoria: "Sagra",
    descrizione: "La più famosa sagra del Cilento, dedicata al fusillo artigianale di Felitto, pasta fresca lavorata a mano su ferro. Dieci giorni di festa con degustazioni, concerti e mercato dei produttori locali.",
    gratuito: true,
    organizzatore: "Pro Loco Felitto",
    immagine: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Felitto_veduta.jpg/1280px-Felitto_veduta.jpg",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Autoctono — Festival del Vino 2026",
    data: "2026-08-16",
    dataFine: "2026-08-18",
    comune: "Vallo della Lucania",
    luogo: "Pellare",
    categoria: "Sagra",
    descrizione: "Festival dedicato ai vini autoctoni del Cilento con degustazioni di Aglianico, Fiano, Falanghina e altre varietà locali. Cantine del territorio, musica e convivialità nella campagna cilentana.",
    gratuito: false,
    prezzo: "Calice degustazione incluso",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Festa del Pane e della Civiltà Contadina 2026",
    data: "2026-08-16",
    dataFine: "2026-08-20",
    comune: "Trentinara",
    luogo: "Centro storico di Trentinara",
    categoria: "Cultura",
    descrizione: "Manifestazione dedicata alla civiltà contadina cilentana con dimostrazioni di antichi mestieri, panificazione tradizionale, prodotti tipici e musica folk. Vista panoramica sulla Piana del Sele.",
    gratuito: true,
    organizzatore: "Pro Loco Trentinara",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "A' Cillisi 2026",
    data: "2026-08-17",
    dataFine: "2026-08-19",
    comune: "Celle di Bulgheria",
    luogo: "Centro storico di Celle di Bulgheria",
    categoria: "Sagra",
    descrizione: "Sagra cilentana con stand gastronomici, prodotti locali, musica e danze popolari. 'A Cillisi' celebra la tradizione culinaria del borgo di Celle di Bulgheria nel cuore del Parco del Cilento.",
    gratuito: true,
    organizzatore: "Pro Loco Celle di Bulgheria",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Ciccimmaretati 2026",
    data: "2026-08-17",
    dataFine: "2026-08-23",
    comune: "Stio",
    luogo: "Centro storico di Stio Cilento",
    categoria: "Sagra",
    descrizione: "La sagra dei ceci e farro di Stio, zuppa tipica cilentana dai sapori antichi. Una settimana di festa nel caratteristico borgo di Stio con degustazioni, concerti e animazione popolare.",
    gratuito: true,
    organizzatore: "Pro Loco Stio",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Gigi Finizio in concerto a Paestum 2026",
    data: "2026-08-18",
    comune: "Capaccio Paestum",
    luogo: "Area Archeologica di Paestum",
    categoria: "Musica",
    descrizione: "Concerto di Gigi Finizio nell'affascinante cornice dell'Area Archeologica di Paestum con i templi greci come sfondo. Una serata di musica napoletana tra storia e magia.",
    gratuito: false,
    prezzo: "A pagamento",
    immagine: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Paestum-_Tempio_di_Nettuno_e_Bassilica.jpg/1280px-Paestum-_Tempio_di_Nettuno_e_Bassilica.jpg",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Cilento Fest 2026",
    data: "2026-08-18",
    dataFine: "2026-08-21",
    comune: "Perito",
    luogo: "Centro storico di Perito",
    categoria: "Musica",
    descrizione: "Festival musicale estivo a Perito con concerti di artisti nazionali e locali, stand gastronomici, mostra d'arte e animazione. Quattro giorni di festa nel cuore del Cilento interno.",
    gratuito: true,
    organizzatore: "Pro Loco Perito",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Festa degli Antichi Sapori 2026",
    data: "2026-08-18",
    dataFine: "2026-08-20",
    comune: "Ascea",
    luogo: "Mandia (Ascea)",
    categoria: "Sagra",
    descrizione: "Sagra dei prodotti tipici cilentani nella frazione di Mandia. Tre giorni con degustazione di formaggi, salumi, conserve, vini locali e pane casereccio, accompagnati da musica popolare.",
    gratuito: true,
    organizzatore: "Pro Loco Ascea",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "La Rocca delle Arti 2026",
    data: "2026-08-22",
    dataFine: "2026-08-24",
    comune: "Roccagloriosa",
    luogo: "Centro storico di Roccagloriosa",
    categoria: "Cultura",
    descrizione: "Festival artistico e culturale nel borgo medievale di Roccagloriosa con mostre d'arte, installazioni, musica live, teatro e incontri con artisti. La rocca diventa palcoscenico di creatività.",
    gratuito: true,
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Festa del Fico Bianco di Giungano 2026",
    data: "2026-08-22",
    dataFine: "2026-08-25",
    comune: "Giungano",
    luogo: "Centro storico di Giungano",
    categoria: "Sagra",
    descrizione: "Sagra dedicata al fico bianco del Cilento, frutto simbolo del territorio e Presidio Slow Food. Degustazioni, marmellate, prodotti essiccati, musica e balli tradizionali nel borgo collinare di Giungano.",
    gratuito: true,
    organizzatore: "Pro Loco Giungano",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Claudio Baglioni in concerto a Paestum 2026",
    data: "2026-08-27",
    comune: "Capaccio Paestum",
    luogo: "Area Archeologica di Paestum",
    categoria: "Musica",
    descrizione: "Concerto di Claudio Baglioni tra i templi greci di Paestum, patrimonio dell'umanità. Uno degli eventi musicali più attesi dell'estate nel Sud Italia.",
    gratuito: false,
    prezzo: "A pagamento",
    organizzatore: "Museo Paestum / Provincia di Salerno",
    immagine: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Paestum-_Tempio_di_Nettuno_e_Bassilica.jpg/1280px-Paestum-_Tempio_di_Nettuno_e_Bassilica.jpg",
    sorgente: "https://www.ilcilentano.it/sagre-ed-eventi-nel-cilento-nel-2026-tutti-gli-appuntamenti/",
  },
  {
    titolo: "Pooh in concerto a Paestum 2026",
    data: "2026-08-29",
    comune: "Capaccio Paestum",
    luogo: "Area Archeologica di Paestum",
    categoria: "Musica",
    descrizione: "Concerto dei Pooh nell'incantevole cornice dei templi di Paestum. Il gruppo storico del rock italiano porta le sue canzoni immortali tra le colonne doriche del tempio di Nettuno.",
    gratuito: false,
    prezzo: "A pagamento",
    immagine: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Paestum-_Tempio_di_Nettuno_e_Bassilica.jpg/1280px-Paestum-_Tempio_di_Nettuno_e_Bassilica.jpg",
    sorgente: "https://www.ilcilentano.it/sagre-ed-eventi-nel-cilento-nel-2026-tutti-gli-appuntamenti/",
  },

  // ══ SETTEMBRE 2026 ════════════════════════════════════════════════════════

  {
    titolo: "Festival degli Antichi Suoni 2026",
    data: "2026-08-30",
    dataFine: "2026-09-01",
    comune: "Novi Velia",
    luogo: "Monte Stella, Novi Velia",
    categoria: "Musica",
    descrizione: "Festival internazionale di musica etnica e popolare sul sacro Monte Stella. Concerti di musicisti provenienti da tutto il Mediterraneo che si esibiscono in un luogo di straordinaria spiritualità e panorama.",
    gratuito: true,
    organizzatore: "Associazione Festival degli Antichi Suoni",
    immagine: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Monte_Stella_-_Cilento.jpg/1280px-Monte_Stella_-_Cilento.jpg",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Fiera della Frecagnola 2026",
    data: "2026-09-04",
    dataFine: "2026-09-08",
    comune: "Cannalonga",
    luogo: "Centro storico di Cannalonga",
    categoria: "Mercato",
    descrizione: "Storica fiera di settembre a Cannalonga con mercato agricolo, mostra zootecnica, prodotti artigianali e gastronomia cilentana. Una delle fiere più tradizionali dell'entroterra.",
    gratuito: true,
    organizzatore: "Pro Loco Cannalonga",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Sagra del Pesce Azzurro di Pioppi 2026",
    data: "2026-09-06",
    dataFine: "2026-09-08",
    comune: "Pollica",
    luogo: "Porto di Pioppi",
    categoria: "Sagra",
    descrizione: "Sagra del pesce azzurro nel pittoresco porto di Pioppi. Alici, sgombri e sardine preparati secondo le ricette tradizionali dei pescatori locali, con musica e atmosfera tipica del Cilento costiero.",
    gratuito: true,
    organizzatore: "Pro Loco Pioppi",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Pesce in Festa 2026",
    data: "2026-09-18",
    dataFine: "2026-09-20",
    comune: "Casal Velino",
    luogo: "Casal Velino Marina",
    categoria: "Sagra",
    descrizione: "Tre giorni di festa dedicati al pescato locale a Casal Velino Marina. Stand con frittura di pesce, impepata di cozze, alici marinate e tutti i sapori del mare cilentano, con musica dal vivo.",
    gratuito: true,
    organizzatore: "Pro Loco Casal Velino Marina",
    sorgente: "https://www.eventinelcilento.it/",
  },

  // ══ NUOVI EVENTI — GIUGNO 2026 ════════════════════════════════════════════

  {
    titolo: "Settimana della Dieta Mediterranea 2026",
    data: "2026-06-07",
    dataFine: "2026-06-13",
    comune: "Pollica",
    luogo: "Pioppi, Pollica",
    categoria: "Cultura",
    descrizione: "Evento internazionale dedicato alla Dieta Mediterranea, riconosciuta dall'UNESCO come patrimonio immateriale dell'umanità. Conferenze, degustazioni, laboratori di cucina tradizionale e convegni scientifici nel borgo dove Ancel Keys scoprì la dieta mediterranea.",
    gratuito: false,
    prezzo: "Ingresso variabile per eventi",
    organizzatore: "Fondazione Dieta Mediterranea",
    immagine: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Pioppi_porto.jpg/1280px-Pioppi_porto.jpg",
    sorgente: "https://www.cilentodiet.com/",
  },
  {
    titolo: "Infiorata del Corpus Domini di Paestum 2026",
    data: "2026-06-14",
    comune: "Capaccio Paestum",
    luogo: "Via Magna Graecia, Paestum",
    categoria: "Religioso",
    descrizione: "Suggestiva infiorata lungo le vie di Paestum per la festa del Corpus Domini. I petali di fiori colorati formano elaborati tappeti floreali con disegni sacri e paesaggistici nelle strade vicino ai templi greci.",
    gratuito: true,
    organizzatore: "Parrocchie di Capaccio Paestum",
    sorgente: "https://www.comune.capaccio-paestum.sa.it",
  },
  {
    titolo: "Vallo Scarlatto 2026",
    data: "2026-06-19",
    dataFine: "2026-06-21",
    comune: "Vallo della Lucania",
    luogo: "Centro storico, Vallo della Lucania",
    categoria: "Cultura",
    descrizione: "Festival medievale e rinascimentale nel centro storico di Vallo della Lucania con rievocazioni in costume, tornei, cortei storici, artigianato e gastronomia d'epoca. Un viaggio nel tempo nel cuore del Cilento.",
    gratuito: true,
    organizzatore: "Comune di Vallo della Lucania",
    sorgente: "https://www.infocilento.it/",
  },
  {
    titolo: "Agropoli Summer Fest 2026",
    data: "2026-06-26",
    dataFine: "2026-08-31",
    comune: "Agropoli",
    luogo: "Lungomare e centro storico, Agropoli",
    categoria: "Musica",
    descrizione: "Lunga estate di concerti, spettacoli, cinema all'aperto, mercatini e animazione nel lungomare e nel centro storico di Agropoli. Il principale appuntamento estivo della capitale del Cilento.",
    gratuito: true,
    organizzatore: "Comune di Agropoli",
    sorgente: "https://www.comune.agropoli.sa.it/",
  },
  {
    titolo: "NotteBianca di Castellabate 2026",
    data: "2026-06-27",
    comune: "Castellabate",
    luogo: "Centro storico di Castellabate",
    categoria: "Cultura",
    descrizione: "Notte bianca nel borgo medievale di Castellabate con negozi aperti fino a tarda notte, musica, street food, mostre d'arte e spettacoli. Serata magica in uno dei borghi più belli d'Italia.",
    gratuito: true,
    organizzatore: "Comune di Castellabate",
    sorgente: "https://www.comune.castellabate.sa.it",
  },

  // ══ NUOVI EVENTI — LUGLIO 2026 ════════════════════════════════════════════

  {
    titolo: "Castellabate Jazz Festival 2026",
    data: "2026-07-10",
    dataFine: "2026-07-12",
    comune: "Castellabate",
    luogo: "Piazza Lucia Pinto, Castellabate",
    categoria: "Musica",
    descrizione: "Festival jazz internazionale nel suggestivo centro storico di Castellabate. Tre serate con musicisti italiani e internazionali nel borgo patrimonio dell'umanità UNESCO, con vista panoramica sul Golfo di Salerno.",
    gratuito: false,
    prezzo: "Ingresso variabile",
    organizzatore: "Associazione Castellabate Jazz",
    sorgente: "https://www.infocilento.it/",
  },
  {
    titolo: "Notte del Museo — Paestum 2026",
    data: "2026-07-18",
    comune: "Capaccio Paestum",
    luogo: "Museo Archeologico Nazionale di Paestum",
    categoria: "Cultura",
    descrizione: "Apertura straordinaria notturna del Museo Archeologico di Paestum con visite guidate ai templi greci illuminati, concerti di musica classica e performance artistiche. Un'esperienza unica tra storia e magia.",
    gratuito: false,
    prezzo: "€5 ingresso speciale",
    organizzatore: "Museo Archeologico Nazionale di Paestum",
    immagine: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Paestum-_Tempio_di_Nettuno_e_Bassilica.jpg/1280px-Paestum-_Tempio_di_Nettuno_e_Bassilica.jpg",
    sorgente: "https://www.museopaestum.beniculturali.it/",
  },
  {
    titolo: "Sapri Folk Festival 2026",
    data: "2026-07-24",
    dataFine: "2026-07-26",
    comune: "Sapri",
    luogo: "Lungomare di Sapri",
    categoria: "Musica",
    descrizione: "Festival di musica popolare e folk sul lungomare di Sapri. Gruppi musicali da tutto il Sud Italia si esibiscono con tamburelli, zampogne e canti tradizionali in riva al mare del Golfo di Policastro.",
    gratuito: true,
    organizzatore: "Pro Loco Sapri",
    sorgente: "https://www.comune.sapri.sa.it",
  },
  {
    titolo: "Sagra del Polpo di Acciaroli 2026",
    data: "2026-07-31",
    dataFine: "2026-08-02",
    comune: "Pollica",
    luogo: "Porto di Acciaroli",
    categoria: "Sagra",
    descrizione: "Tre giorni di festa dedicati al polpo verace del Cilento nel caratteristico porto di Acciaroli, uno dei borghi più belli d'Italia. Degustazioni, sagra, musica popolare e la tradizione dei pescatori locali.",
    gratuito: true,
    organizzatore: "Pro Loco Acciaroli",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Cinema sotto le Stelle — Vallo di Diano 2026",
    data: "2026-07-01",
    dataFine: "2026-08-31",
    comune: "Sala Consilina",
    luogo: "Vari borghi del Vallo di Diano",
    categoria: "Cultura",
    descrizione: "Rassegna estiva di cinema all'aperto nei borghi del Vallo di Diano. Film d'autore, anteprime e grandi classici proiettati nelle piazze e nei cortili storici di Sala Consilina, Teggiano, Padula e degli altri comuni.",
    gratuito: false,
    prezzo: "€3–5 a proiezione",
    organizzatore: "Associazioni culturali Vallo di Diano",
    sorgente: "https://www.ondanews.it/",
  },
  {
    titolo: "Palinuro Summer Events 2026",
    data: "2026-07-15",
    dataFine: "2026-08-20",
    comune: "Centola",
    luogo: "Palinuro",
    categoria: "Musica",
    descrizione: "Calendario estivo di eventi a Palinuro: concerti in piazza, spettacoli di cabaret, serate DJ sul lungomare, degustazioni di prodotti locali e animazione per famiglie. Il cuore pulsante dell'estate nel Golfo di Policastro.",
    gratuito: true,
    organizzatore: "Comune di Centola / Pro Loco Palinuro",
    sorgente: "https://www.infocilento.it/",
  },
  {
    titolo: "Grotte di Castelcivita — Notti Magiche 2026",
    data: "2026-07-04",
    dataFine: "2026-07-25",
    comune: "Castelcivita",
    luogo: "Grotta di Castelcivita",
    categoria: "Natura",
    descrizione: "Aperture serali straordinarie della Grotta di Castelcivita con visite guidate suggestive alle stalattiti illuminate e concerto di musica da camera all'interno della grotta. Un'esperienza unica e spettacolare.",
    gratuito: false,
    prezzo: "€12 visita guidata serale",
    organizzatore: "Grotta di Castelcivita s.r.l.",
    sorgente: "https://www.grottadicastelcivita.com/",
  },

  // ══ NUOVI EVENTI — AGOSTO 2026 ════════════════════════════════════════════

  {
    titolo: "Festa della Madonna del Granato 2026",
    data: "2026-08-15",
    comune: "Capaccio Paestum",
    luogo: "Santuario della Madonna del Granato, Capaccio",
    categoria: "Religioso",
    descrizione: "Una delle feste religiose più sentite del Cilento: il 15 agosto migliaia di fedeli salgono in processione al Santuario della Madonna del Granato sul Monte Soprano. Messa solenne, processione, fuochi d'artificio e festa popolare.",
    gratuito: true,
    organizzatore: "Parrocchia di Capaccio",
    immagine: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Capaccio_Vecchio_panorama.jpg/1280px-Capaccio_Vecchio_panorama.jpg",
    sorgente: "https://www.comune.capaccio-paestum.sa.it",
  },
  {
    titolo: "Ferragosto a Palinuro 2026",
    data: "2026-08-14",
    dataFine: "2026-08-16",
    comune: "Centola",
    luogo: "Palinuro, Golfo di Policastro",
    categoria: "Musica",
    descrizione: "Tre giorni di festeggiamenti per Ferragosto a Palinuro: fuochi d'artificio sul mare, concerti in piazza, sagre del pesce, gare di nuoto in mare aperto e animazione notturna sul lungomare.",
    gratuito: true,
    organizzatore: "Comune di Centola",
    sorgente: "https://www.infocilento.it/",
  },
  {
    titolo: "Sagra del Fagiolo di Controne 2026",
    data: "2026-08-20",
    dataFine: "2026-08-23",
    comune: "Controne",
    luogo: "Centro storico di Controne",
    categoria: "Sagra",
    descrizione: "Sagra dedicata al fagiolo di Controne, legume Presidio Slow Food tra i più pregiati d'Italia. Zuppe, pasta e fagioli, minestre e piatti tradizionali della cucina cilentana negli Alburni, con musica e convivialità.",
    gratuito: true,
    organizzatore: "Pro Loco Controne",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Sagra del Fico Bianco del Cilento — Pisciotta 2026",
    data: "2026-08-28",
    dataFine: "2026-08-30",
    comune: "Pisciotta",
    luogo: "Centro storico di Pisciotta",
    categoria: "Sagra",
    descrizione: "Tre giorni dedicati al fico bianco del Cilento DOP nel borgo medievale di Pisciotta. Degustazioni di fichi secchi, confetture, dolci tipici, pane con i fichi e prodotti locali, con musica e panorami sul mare.",
    gratuito: true,
    organizzatore: "Pro Loco Pisciotta",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Estate a Castellabate — Concerti e Spettacoli 2026",
    data: "2026-08-01",
    dataFine: "2026-08-31",
    comune: "Castellabate",
    luogo: "Castello Medievale e Piazze di Castellabate",
    categoria: "Musica",
    descrizione: "Un mese di concerti, spettacoli teatrali, presentazioni di libri e mostre d'arte nel magnifico scenario del castello medievale di Castellabate e nelle piazze del borgo. Una delle proposte culturali più ricche del Cilento costiero.",
    gratuito: false,
    prezzo: "Ingresso variabile per evento",
    organizzatore: "Comune di Castellabate",
    sorgente: "https://www.comune.castellabate.sa.it",
  },
  {
    titolo: "Festival dell'Acqua e del Fuoco — Grotte Pertosa 2026",
    data: "2026-08-07",
    dataFine: "2026-08-09",
    comune: "Pertosa",
    luogo: "Grotte di Pertosa-Auletta",
    categoria: "Natura",
    descrizione: "Spettacolo unico alle Grotte di Pertosa-Auletta: navigazione sul fiume sotterraneo con illuminazioni speciali, proiezioni sulle stalattiti e performance musicali all'interno della grotta. Un'esperienza di rara bellezza.",
    gratuito: false,
    prezzo: "€15 visita speciale serale",
    organizzatore: "Grotte di Pertosa-Auletta",
    sorgente: "https://www.grottedipertosa-auletta.it/",
  },
  {
    titolo: "Premio Letterario Agropoli 2026",
    data: "2026-08-25",
    dataFine: "2026-08-27",
    comune: "Agropoli",
    luogo: "Castello Aragonese, Agropoli",
    categoria: "Cultura",
    descrizione: "Premio letterario nazionale con presentazioni di libri, incontri con autori e dibattiti culturali nel suggestivo Castello Aragonese di Agropoli. Tre serate di letteratura e cultura affacciate sul Cilento.",
    gratuito: true,
    organizzatore: "Comune di Agropoli / Associazione Culturale",
    sorgente: "https://www.comune.agropoli.sa.it/",
  },

  // ══ NUOVI EVENTI — SETTEMBRE 2026 ════════════════════════════════════════

  {
    titolo: "Festa di San Matteo — Patrono di Agropoli 2026",
    data: "2026-09-20",
    dataFine: "2026-09-21",
    comune: "Agropoli",
    luogo: "Centro storico e porto di Agropoli",
    categoria: "Religioso",
    descrizione: "Festa patronale di San Matteo ad Agropoli: processione a mare con la statua del Santo, messa solenne, banda musicale, luna park e fuochi d'artificio. La festa più importante dell'anno per la comunità di Agropoli.",
    gratuito: true,
    organizzatore: "Parrocchia San Marco Evangelista, Agropoli",
    sorgente: "https://www.comune.agropoli.sa.it/",
  },
  {
    titolo: "Giornate Europee del Patrimonio — Paestum 2026",
    data: "2026-09-26",
    dataFine: "2026-09-27",
    comune: "Capaccio Paestum",
    luogo: "Parco Archeologico di Paestum",
    categoria: "Cultura",
    descrizione: "Aperture straordinarie e gratuite del Parco Archeologico di Paestum in occasione delle Giornate Europee del Patrimonio. Visite guidate, laboratori per bambini, conferenze e attività culturali sui templi greci.",
    gratuito: true,
    organizzatore: "Parco Archeologico di Paestum e Velia",
    immagine: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Paestum-_Tempio_di_Nettuno_e_Bassilica.jpg/1280px-Paestum-_Tempio_di_Nettuno_e_Bassilica.jpg",
    sorgente: "https://www.museopaestum.beniculturali.it/",
  },
  {
    titolo: "Sagra della Castagna — Sanza 2026",
    data: "2026-10-03",
    dataFine: "2026-10-04",
    comune: "Sanza",
    luogo: "Centro storico di Sanza",
    categoria: "Sagra",
    descrizione: "Sagra autunnale dedicata alla castagna del Cilento nel suggestivo borgo di Sanza, ai piedi del Monte Cervati. Caldarroste, dolci, castagne bollite, miele e prodotti del bosco con musica folk e animazione.",
    gratuito: true,
    organizzatore: "Pro Loco Sanza",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Fiera di Mezzosettembre — Sala Consilina 2026",
    data: "2026-09-13",
    dataFine: "2026-09-15",
    comune: "Sala Consilina",
    luogo: "Centro storico, Sala Consilina",
    categoria: "Mercato",
    descrizione: "Storica fiera di settembre a Sala Consilina con bancarelle di prodotti agricoli, artigianato locale, mostra zootecnica, gastronomia cilentana e animazione. Una delle fiere più tradizionali del Vallo di Diano.",
    gratuito: true,
    organizzatore: "Comune di Sala Consilina",
    sorgente: "https://www.comune.sala-consilina.sa.it",
  },
  {
    titolo: "Sagra dei Funghi Porcini — Roscigno 2026",
    data: "2026-10-10",
    dataFine: "2026-10-11",
    comune: "Roscigno",
    luogo: "Roscigno Vecchia (il paese fantasma)",
    categoria: "Sagra",
    descrizione: "Sagra dei funghi porcini in uno dei luoghi più suggestivi del Cilento: Roscigno Vecchia, il 'paese fantasma' abbandonato alla fine dell'Ottocento. Degustazioni di funghi, pasta, zuppa e prodotti del bosco tra le case abbandonate.",
    gratuito: true,
    organizzatore: "Pro Loco Roscigno",
    sorgente: "https://www.infocilento.it/",
  },
  {
    titolo: "Cilento Enduro — Gara di Mountain Bike 2026",
    data: "2026-09-05",
    dataFine: "2026-09-06",
    comune: "Vallo della Lucania",
    luogo: "Monti Alburni e Cilento interno",
    categoria: "Sport",
    descrizione: "Gara di mountain bike enduro tra i sentieri dei Monti Alburni e del Parco del Cilento. Percorsi per tutte le categorie attraverso borghi, foreste e panorami mozzafiato. Evento aperto ad amatori e professionisti.",
    gratuito: false,
    prezzo: "Iscrizione gara €25–40",
    sorgente: "https://www.parcoregionalecilento.it/",
  },

] as const;
