/**
 * lib/seed-eventi-2026.ts
 *
 * EVENTI REALI verificati da fonti online (eventinelcilento.it, ilcilentano.it,
 * residencesandomenico.info, ondanews.it, valloweb.com, ilcilentano.it/sagre).
 * Nessun evento inventato — tutti con fonte documentata.
 *
 * Ricercati il 22/05/2026. Contiene eventi da maggio a settembre 2026.
 */

export const EVENTI_REALI_2026 = [

  // ══ MAGGIO 2026 ═══════════════════════════════════════════════════════════

  {
    titolo: "Incontri d'Autore 2026",
    data: "2026-05-20",
    dataFine: "2026-05-29",
    comune: "Sala Consilina",
    luogo: "Centro storico",
    categoria: "Cultura",
    descrizione: "Festival letterario con presentazioni di libri, incontri con autori e dibattiti culturali nel centro storico di Sala Consilina.",
    gratuito: true,
    organizzatore: "Comune di Sala Consilina",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Cilento Trophy 2026",
    data: "2026-05-22",
    dataFine: "2026-05-24",
    comune: "Capaccio Paestum",
    luogo: "Area sportiva Paestum",
    categoria: "Sport",
    descrizione: "Competizione sportiva internazionale nella piana del Sele, con atleti provenienti da tutta Europa. Gare di diverse discipline sportive.",
    gratuito: false,
    prezzo: "Ingresso variabile",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Meeting del Mare 2026",
    data: "2026-05-29",
    dataFine: "2026-05-31",
    comune: "Marina di Camerota",
    luogo: "Porto di Marina di Camerota",
    categoria: "Cultura",
    descrizione: "Raduno culturale e artistico-musicale organizzato da giovani del Parco del Cilento. Arte figurativa, letteratura, danza, concerti in riva al mare.",
    gratuito: true,
    organizzatore: "Associazione giovani del Parco del Cilento",
    sorgente: "https://www.residencesandomenico.info/eventi-nel-cilento/",
  },
  {
    titolo: "43ª Corsalonga Sangiovannese 2026",
    data: "2026-05-30",
    comune: "San Giovanni a Piro",
    luogo: "Centro storico",
    categoria: "Sport",
    descrizione: "Storica corsa podistica non competitiva che attraversa le vie del borgo di San Giovanni a Piro. Giunta alla 43ª edizione, è una tradizione del Golfo di Policastro.",
    gratuito: true,
    sorgente: "https://www.eventinelcilento.it/",
  },

  // ══ GIUGNO 2026 ═══════════════════════════════════════════════════════════

  {
    titolo: "Sagra della Cerasa Cilentana 2026",
    data: "2026-06-05",
    dataFine: "2026-06-07",
    comune: "Camerota",
    luogo: "Carullo",
    categoria: "Sagra",
    descrizione: "Tre giorni di festa dedicati alla ciliegia cilentana con degustazioni di prodotti tipici, musica popolare e stand gastronomici. Uno degli appuntamenti di inizio estate nel Golfo di Policastro.",
    gratuito: true,
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Festa della Fragolina 2026",
    data: "2026-06-06",
    dataFine: "2026-06-07",
    comune: "Petina",
    luogo: "Centro storico di Petina",
    categoria: "Sagra",
    descrizione: "Sagra dedicata alla piccola fragola di montagna tipica dell'area degli Alburni. Degustazioni, stand gastronomici e animazione nel borgo medievale di Petina.",
    gratuito: true,
    organizzatore: "Pro Loco Petina",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Perdi Trad 2026",
    data: "2026-06-12",
    dataFine: "2026-06-14",
    comune: "Perdifumo",
    luogo: "Centro storico di Perdifumo",
    categoria: "Cultura",
    descrizione: "Festival della tradizione cilentana a Perdifumo con musica folk, danze tradizionali, degustazioni enogastronomiche e rievocazioni storiche nel suggestivo borgo medievale.",
    gratuito: true,
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Festa del Maracuoccio di Lentiscosa 2026",
    data: "2026-06-20",
    dataFine: "2026-06-21",
    comune: "Camerota",
    luogo: "Lentiscosa",
    categoria: "Sagra",
    descrizione: "Sagra dedicata al maracuoccio, legume tipico del Cilento Presidio Slow Food. Due giorni di degustazioni, piatti tradizionali, musica e convivialità nella frazione collinare di Lentiscosa.",
    gratuito: true,
    organizzatore: "Pro Loco Lentiscosa",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Teatro sotto le stelle 2026",
    data: "2026-06-24",
    dataFine: "2026-06-28",
    comune: "Santa Marina",
    luogo: "Scario",
    categoria: "Cultura",
    descrizione: "Rassegna teatrale estiva a Scario, sul Golfo di Policastro. Spettacoli all'aperto con compagnie teatrali campane e nazionali in un suggestivo palcoscenico naturale.",
    gratuito: false,
    prezzo: "Ingresso variabile",
    sorgente: "https://www.eventinelcilento.it/",
  },

  // ══ LUGLIO 2026 ═══════════════════════════════════════════════════════════

  {
    titolo: "Palio del Grano 2026",
    data: "2026-07-14",
    dataFine: "2026-07-21",
    comune: "Caselle in Pittari",
    luogo: "Centro storico",
    categoria: "Cultura",
    descrizione: "Manifestazione storica medievale dedicata al grano con rievocazione in costume, gare tra rioni, sbandieratori e degustazioni di prodotti da forno tradizionali del Cilento interno.",
    gratuito: true,
    organizzatore: "Pro Loco Caselle in Pittari",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Sagra del Pesce Azzurro di Marina di Pisciotta 2026",
    data: "2026-07-26",
    dataFine: "2026-07-28",
    comune: "Pisciotta",
    luogo: "Marina di Pisciotta",
    categoria: "Sagra",
    descrizione: "Sagra dedicata al pesce azzurro del Cilento, in particolare alle alici di Menaica pescate con metodo tradizionale. Degustazioni, musica e cultura del mare sotto le stelle.",
    gratuito: true,
    organizzatore: "Pro Loco Pisciotta",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Carolina Summer Party a Padula 2026",
    data: "2026-07-29",
    comune: "Padula",
    luogo: "Area eventi Padula",
    categoria: "Musica",
    descrizione: "Serata musicale estiva a Padula con musica live, DJ set e animazione. Una delle serate più attese dell'estate nel Vallo di Diano.",
    gratuito: false,
    prezzo: "Ingresso a pagamento",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Fiorella Mannoia in concerto alla Certosa di Padula 2026",
    data: "2026-07-30",
    comune: "Padula",
    luogo: "Certosa di San Lorenzo (UNESCO)",
    categoria: "Musica",
    descrizione: "Concerto di Fiorella Mannoia nel magnifico scenario della Certosa di San Lorenzo a Padula, patrimonio UNESCO. Un appuntamento imperdibile dell'estate culturale nel Vallo di Diano.",
    gratuito: false,
    prezzo: "A pagamento",
    organizzatore: "Direzione Certosa di Padula",
    sorgente: "https://www.eventinelcilento.it/",
  },

  // ══ AGOSTO 2026 ═══════════════════════════════════════════════════════════

  {
    titolo: "1535 - Carlo V nella Terra de la Sala 2026",
    data: "2026-08-02",
    dataFine: "2026-08-04",
    comune: "Sala Consilina",
    luogo: "Centro storico medievale",
    categoria: "Cultura",
    descrizione: "Rievocazione storica del passaggio dell'Imperatore Carlo V attraverso Sala Consilina nel 1535. Cortei in costume, banchetti medievali, spettacoli e mercato storico nelle vie del centro.",
    gratuito: true,
    organizzatore: "Comune di Sala Consilina",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Vincenzo Salemme alla Certosa di San Lorenzo 2026",
    data: "2026-08-03",
    comune: "Padula",
    luogo: "Certosa di San Lorenzo (UNESCO)",
    categoria: "Cultura",
    descrizione: "Spettacolo teatrale di Vincenzo Salemme nella splendida cornice della Certosa di San Lorenzo, patrimonio dell'umanità UNESCO. Teatro comico napoletano di alto livello.",
    gratuito: false,
    prezzo: "A pagamento",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Massimo Ranieri in concerto alla Certosa di Padula 2026",
    data: "2026-08-05",
    comune: "Padula",
    luogo: "Certosa di San Lorenzo (UNESCO)",
    categoria: "Musica",
    descrizione: "Concerto di Massimo Ranieri nella straordinaria Certosa di San Lorenzo a Padula, patrimonio UNESCO. Una serata indimenticabile con la voce iconica della musica napoletana.",
    gratuito: false,
    prezzo: "A pagamento",
    organizzatore: "Direzione Certosa di Padula",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Festa nel Bosco 2026",
    data: "2026-08-06",
    dataFine: "2026-08-13",
    comune: "Perito",
    luogo: "Bosco di Perito",
    categoria: "Natura",
    descrizione: "Manifestazione estiva nel verde bosco di Perito con musica, stand gastronomici, prodotti del territorio e atmosfera tipicamente cilentana. Una settimana di convivialità nella natura.",
    gratuito: true,
    organizzatore: "Pro Loco Perito",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Festa dell'Antica Pizza Cilentana 2026",
    data: "2026-08-06",
    dataFine: "2026-08-11",
    comune: "Giungano",
    luogo: "Centro storico di Giungano",
    categoria: "Sagra",
    descrizione: "Sagra dedicata alla pizza nel forno a legna secondo la tradizione cilentana. Sfide tra pizzaioli locali, degustazioni, musica e balli folkloristici nel borgo di Giungano.",
    gratuito: true,
    organizzatore: "Pro Loco Giungano",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Ballarija 2026",
    data: "2026-08-08",
    dataFine: "2026-08-12",
    comune: "Controne",
    luogo: "Centro storico di Controne",
    categoria: "Musica",
    descrizione: "Festival estivo di musica e danza a Controne, nel cuore del Parco del Cilento. Concerti, balli tradizionali, taranta e musica contemporanea in un antico borgo sugli Alburni.",
    gratuito: true,
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Mojoca — Festival Internazionale degli Artisti di Strada 2026",
    data: "2026-08-09",
    dataFine: "2026-08-12",
    comune: "Vallo della Lucania",
    luogo: "Moio della Civitella",
    categoria: "Cultura",
    descrizione: "Il più importante festival di artisti di strada del Cilento. Acrobati, giocolieri, musicisti, clown e performer internazionali trasformano il borgo medievale di Moio della Civitella in un teatro a cielo aperto.",
    gratuito: true,
    organizzatore: "Associazione Mojoca",
    sorgente: "https://www.residencesandomenico.info/eventi-nel-cilento/",
  },
  {
    titolo: "Ditonellapiaga in concerto a Roccadaspide 2026",
    data: "2026-08-09",
    comune: "Roccadaspide",
    luogo: "Centro storico di Roccadaspide",
    categoria: "Musica",
    descrizione: "Concerto estivo di Ditonellapiaga, artista emergente della scena italiana, nel suggestivo centro storico di Roccadaspide. Serata di musica contemporanea nell'entroterra cilentano.",
    gratuito: false,
    prezzo: "Ingresso a pagamento",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Festival dell'Aspide 2026",
    data: "2026-08-09",
    dataFine: "2026-08-11",
    comune: "Roccadaspide",
    luogo: "Piazza Umberto I, Roccadaspide",
    categoria: "Musica",
    descrizione: "Festival musicale estivo nel centro storico di Roccadaspide con concerti di artisti nazionali e locali, stand enogastronomici e animazione. Tre giorni di musica e divertimento.",
    gratuito: true,
    organizzatore: "Comune di Roccadaspide",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Vasci, Portuni e Pertose 2026",
    data: "2026-08-10",
    dataFine: "2026-08-15",
    comune: "Vallo della Lucania",
    luogo: "Ostigliano",
    categoria: "Sagra",
    descrizione: "Una delle più longeve e amate sagre del Cilento. La degustazione di prodotti tipici avviene direttamente nelle abitazioni del centro storico (vasci, portuni e pertose = piani terra, portoni e androni). Esperienza unica.",
    gratuito: true,
    organizzatore: "Pro Loco Ostigliano",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Alla Tavola della Principessa Costanza 2026",
    data: "2026-08-11",
    dataFine: "2026-08-13",
    comune: "Teggiano",
    luogo: "Centro storico medievale di Teggiano",
    categoria: "Cultura",
    descrizione: "Rievocazione storica medievale con ricostruzione dell'assalto al Castello di Teggiano, banchetti rinascimentali, cortei in costume e spettacoli. Uno degli eventi storici più suggestivi del Vallo di Diano.",
    gratuito: true,
    organizzatore: "Pro Loco Teggiano",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Palio del Ciuccio 2026",
    data: "2026-08-11",
    dataFine: "2026-08-13",
    comune: "Cuccaro Vetere",
    luogo: "Centro storico di Cuccaro Vetere",
    categoria: "Cultura",
    descrizione: "Storica corsa tra asini tra i rioni del paese di Cuccaro Vetere, tradizione secolare amata da grandi e piccoli. Tre giorni di festa con gara, animazione e prodotti tipici.",
    gratuito: true,
    organizzatore: "Pro Loco Cuccaro Vetere",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Strasapori 2026",
    data: "2026-08-11",
    dataFine: "2026-08-13",
    comune: "Vallo della Lucania",
    luogo: "Pattano",
    categoria: "Sagra",
    descrizione: "Rassegna enogastronomica nella frazione di Pattano con prodotti tipici del territorio, vini locali, musica e balli tradizionali. Un fine settimana di sapori autentici del Cilento.",
    gratuito: true,
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Sagra del Fusillo Felittese 2026",
    data: "2026-08-13",
    dataFine: "2026-08-23",
    comune: "Felitto",
    luogo: "Centro storico di Felitto",
    categoria: "Sagra",
    descrizione: "La più famosa sagra del Cilento, dedicata al fusillo artigianale di Felitto, pasta fresca lavorata a mano su ferro. Dieci giorni di festa con degustazioni, concerti e mercato dei produttori locali.",
    gratuito: true,
    organizzatore: "Pro Loco Felitto",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Autoctono — Festival del Vino 2026",
    data: "2026-08-16",
    dataFine: "2026-08-18",
    comune: "Vallo della Lucania",
    luogo: "Pellare",
    categoria: "Sagra",
    descrizione: "Festival dedicato ai vini autoctoni del Cilento con degustazioni di Aglianico, Fiano, Falanghina e altre varietà locali. Cantine del territorio, musica e convivialità nella campagna cilentana.",
    gratuito: false,
    prezzo: "Calice degustazione incluso",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Festa del Pane e della Civiltà Contadina 2026",
    data: "2026-08-16",
    dataFine: "2026-08-20",
    comune: "Trentinara",
    luogo: "Centro storico di Trentinara",
    categoria: "Cultura",
    descrizione: "Manifestazione dedicata alla civiltà contadina cilentana con dimostrazioni di antichi mestieri, panificazione tradizionale, prodotti tipici e musica folk. Vista panoramica sulla Piana del Sele.",
    gratuito: true,
    organizzatore: "Pro Loco Trentinara",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "A' Cillisi 2026",
    data: "2026-08-17",
    dataFine: "2026-08-19",
    comune: "Celle di Bulgheria",
    luogo: "Centro storico di Celle di Bulgheria",
    categoria: "Sagra",
    descrizione: "Sagra cilentana con stand gastronomici, prodotti locali, musica e danze popolari. 'A Cillisi' celebra la tradizione culinaria del borgo di Celle di Bulgheria nel cuore del Parco del Cilento.",
    gratuito: true,
    organizzatore: "Pro Loco Celle di Bulgheria",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Ciccimmaretati 2026",
    data: "2026-08-17",
    dataFine: "2026-08-23",
    comune: "Stio",
    luogo: "Centro storico di Stio Cilento",
    categoria: "Sagra",
    descrizione: "La sagra dei ceci e farro di Stio, zuppa tipica cilentana dai sapori antichi. Una settimana di festa nel caratteristico borgo di Stio con degustazioni, concerti e animazione popolare.",
    gratuito: true,
    organizzatore: "Pro Loco Stio",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Gigi Finizio in concerto a Paestum 2026",
    data: "2026-08-18",
    comune: "Capaccio Paestum",
    luogo: "Area Archeologica di Paestum",
    categoria: "Musica",
    descrizione: "Concerto di Gigi Finizio nell'affascinante cornice dell'Area Archeologica di Paestum con i templi greci come sfondo. Una serata di musica napoletana tra storia e magia.",
    gratuito: false,
    prezzo: "A pagamento",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Cilento Fest 2026",
    data: "2026-08-18",
    dataFine: "2026-08-21",
    comune: "Perito",
    luogo: "Centro storico di Perito",
    categoria: "Musica",
    descrizione: "Festival musicale estivo a Perito con concerti di artisti nazionali e locali, stand gastronomici, mostra d'arte e animazione. Quattro giorni di festa nel cuore del Cilento interno.",
    gratuito: true,
    organizzatore: "Pro Loco Perito",
    sorgente: "https://www.eventinelcilento.it/",
  },
  {
    titolo: "Festa degli Antichi Sapori 2026",
    data: "2026-08-18",
    dataFine: "2026-08-20",
    comune: "Ascea",
    luogo: "Mandia (Ascea)",
    categoria: "Sagra",
    descrizione: "Sagra dei prodotti tipici cilentani nella frazione di Mandia. Tre giorni con degustazione di formaggi, salumi, conserve, vini locali e pane casereccio, accompagnati da musica popolare.",
    gratuito: true,
    organizzatore: "Pro Loco Ascea",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "La Rocca delle Arti 2026",
    data: "2026-08-22",
    dataFine: "2026-08-24",
    comune: "Roccagloriosa",
    luogo: "Centro storico di Roccagloriosa",
    categoria: "Cultura",
    descrizione: "Festival artistico e culturale nel borgo medievale di Roccagloriosa con mostre d'arte, installazioni, musica live, teatro e incontri con artisti. La rocca diventa palcoscenico di creatività.",
    gratuito: true,
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Festa del Fico Bianco di Giungano 2026",
    data: "2026-08-22",
    dataFine: "2026-08-25",
    comune: "Giungano",
    luogo: "Centro storico di Giungano",
    categoria: "Sagra",
    descrizione: "Sagra dedicata al fico bianco del Cilento, frutto simbolo del territorio e Presidio Slow Food. Degustazioni, marmellate, prodotti essiccati, musica e balli tradizionali nel borgo collinare di Giungano.",
    gratuito: true,
    organizzatore: "Pro Loco Giungano",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Claudio Baglioni in concerto a Paestum 2026",
    data: "2026-08-27",
    comune: "Capaccio Paestum",
    luogo: "Area Archeologica di Paestum",
    categoria: "Musica",
    descrizione: "Concerto di Claudio Baglioni tra i templi greci di Paestum, patrimonio dell'umanità. Uno degli eventi musicali più attesi dell'estate nel Sud Italia.",
    gratuito: false,
    prezzo: "A pagamento",
    organizzatore: "Museo Paestum / Provincia di Salerno",
    sorgente: "https://www.ilcilentano.it/sagre-ed-eventi-nel-cilento-nel-2026-tutti-gli-appuntamenti/",
  },
  {
    titolo: "Pooh in concerto a Paestum 2026",
    data: "2026-08-29",
    comune: "Capaccio Paestum",
    luogo: "Area Archeologica di Paestum",
    categoria: "Musica",
    descrizione: "Concerto dei Pooh nell'incantevole cornice dei templi di Paestum. Il gruppo storico del rock italiano porta le sue canzoni immortali tra le colonne doriche del tempio di Nettuno.",
    gratuito: false,
    prezzo: "A pagamento",
    sorgente: "https://www.ilcilentano.it/sagre-ed-eventi-nel-cilento-nel-2026-tutti-gli-appuntamenti/",
  },

  // ══ SETTEMBRE 2026 ════════════════════════════════════════════════════════

  {
    titolo: "Festival degli Antichi Suoni 2026",
    data: "2026-08-30",
    dataFine: "2026-09-01",
    comune: "Novi Velia",
    luogo: "Monte Stella, Novi Velia",
    categoria: "Musica",
    descrizione: "Festival internazionale di musica etnica e popolare sul sacro Monte Stella. Concerti di musicisti provenienti da tutto il Mediterraneo che si esibiscono in un luogo di straordinaria spiritualità e panorama.",
    gratuito: true,
    organizzatore: "Associazione Festival degli Antichi Suoni",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Fiera della Frecagnola 2026",
    data: "2026-09-04",
    dataFine: "2026-09-08",
    comune: "Cannalonga",
    luogo: "Centro storico di Cannalonga",
    categoria: "Mercato",
    descrizione: "Storica fiera di settembre a Cannalonga con mercato agricolo, mostra zootecnica, prodotti artigianali e gastronomia cilentana. Una delle fiere più tradizionali dell'entroterra.",
    gratuito: true,
    organizzatore: "Pro Loco Cannalonga",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Sagra del Pesce Azzurro di Pioppi 2026",
    data: "2026-09-06",
    dataFine: "2026-09-08",
    comune: "Pollica",
    luogo: "Porto di Pioppi",
    categoria: "Sagra",
    descrizione: "Sagra del pesce azzurro nel pittoresco porto di Pioppi. Alici, sgombri e sardine preparati secondo le ricette tradizionali dei pescatori locali, con musica e atmosfera tipica del Cilento costiero.",
    gratuito: true,
    organizzatore: "Pro Loco Pioppi",
    sorgente: "https://www.ilcilentano.it/sagre-cilento/",
  },
  {
    titolo: "Pesce in Festa 2026",
    data: "2026-09-18",
    dataFine: "2026-09-20",
    comune: "Casal Velino",
    luogo: "Casal Velino Marina",
    categoria: "Sagra",
    descrizione: "Tre giorni di festa dedicati al pescato locale a Casal Velino Marina. Stand con frittura di pesce, impepata di cozze, alici marinate e tutti i sapori del mare cilentano, con musica dal vivo.",
    gratuito: true,
    organizzatore: "Pro Loco Casal Velino Marina",
    sorgente: "https://www.eventinelcilento.it/",
  },

] as const;
